"""
Constants and curriculum data for Pimsleur lessons.
"""

# Lesson timing constants (in seconds)
# Based on analysis of original Pimsleur Icelandic Unit 1 transcript
LESSON_DURATION_TARGET = 1800  # 30 minutes
PAUSE_ANTICIPATION = 3.5  # Pause for user to formulate response (was 4)
PAUSE_REPETITION = 2.5  # Pause for user to repeat (matches original ~2.1-2.8s)
PAUSE_BETWEEN_SEGMENTS = 1.2  # Small pause between segments
PAUSE_BETWEEN_WORDS = 2.2  # Pause between new word introduction

# Spaced repetition intervals (in seconds from word introduction)
SPACED_REPETITION_INTERVALS = [5, 25, 120, 600, 1200]  # 5s, 25s, 2min, 10min, 20min

# Cross-lesson review: which previous lessons to review from
# For lesson N, review vocabulary from lessons N-offset
CROSS_LESSON_REVIEW_OFFSETS = [1, 2, 5, 10]

# Voice configuration
VOICES = {
    "narrator": {
        "voice_id": "ai3-Jony",
        "language_code": "en-US",
        "description": "English narrator for instructions",
    },
    "native_female_is": {
        "voice_id": "ai3-is-IS-Svana",
        "language_code": "is-IS",
        "description": "Icelandic female native speaker",
    },
    "native_male_is": {
        "voice_id": "ai3-is-IS-Ulfr",
        "language_code": "is-IS",
        "description": "Icelandic male native speaker",
    },
    "native_female_de": {
        "voice_id": "pro1-Helena",
        "language_code": "de-DE",
        "description": "German female native speaker",
    },
    "native_male_de": {
        "voice_id": "pro1-Thomas",
        "language_code": "de-DE",
        "description": "German male native speaker",
    },
}

# Vocabulary curriculum by CEFR level
VOCABULARY_CURRICULUM = {
    "A1": {
        "total_vocabulary": 300,
        "new_words_per_lesson": 10,
        "review_words_per_lesson": 8,
        "sentence_length_max": 8,
        "themes": [
            # Lessons 1-5: Basics
            "greetings_and_farewells",
            "introductions",
            "numbers_1_to_10",
            "yes_no_thanks",
            "basic_questions",
            # Lessons 6-10: People & Places
            "family_members",
            "countries_and_nationalities",
            "professions_basic",
            "places_in_city",
            "directions_basic",
            # Lessons 11-15: Daily Life
            "time_and_days",
            "food_and_drinks_basic",
            "shopping_basic",
            "weather_basic",
            "colors",
            # Lessons 16-20: Actions
            "daily_routines",
            "common_verbs",
            "likes_and_dislikes",
            "abilities",
            "needs_and_wants",
            # Lessons 21-25: Social
            "polite_expressions",
            "at_restaurant",
            "at_hotel",
            "telephone_basic",
            "emergencies",
            # Lessons 26-30: Review & Integration
            "travel_phrases",
            "small_talk",
            "review_greetings_intro",
            "review_daily_life",
            "comprehensive_review",
        ],
    },
    "A2": {
        "total_vocabulary": 450,
        "new_words_per_lesson": 15,
        "review_words_per_lesson": 12,
        "sentence_length_max": 12,
        "themes": [
            # Lessons 1-5: Expanding Basics
            "numbers_to_100",
            "months_and_dates",
            "describing_people",
            "describing_places",
            "describing_things",
            # Lessons 6-10: Activities
            "hobbies_and_sports",
            "entertainment",
            "weekend_activities",
            "holidays",
            "celebrations",
            # Lessons 11-15: Practical Situations
            "at_doctor",
            "at_pharmacy",
            "at_bank",
            "at_post_office",
            "public_transport",
            # Lessons 16-20: Home & Work
            "rooms_and_furniture",
            "household_chores",
            "workplace_vocabulary",
            "colleagues_and_meetings",
            "schedules",
            # Lessons 21-25: Communication
            "opinions_and_preferences",
            "making_plans",
            "giving_directions",
            "complaints_and_requests",
            "comparisons",
            # Lessons 26-30: Integration
            "storytelling_past",
            "future_plans",
            "review_practical",
            "review_communication",
            "comprehensive_review",
        ],
    },
    "B1": {
        "total_vocabulary": 750,
        "new_words_per_lesson": 25,
        "review_words_per_lesson": 18,
        "sentence_length_max": 18,
        "themes": [
            # Lessons 1-5: Abstract Concepts
            "emotions_and_feelings",
            "relationships",
            "personality_traits",
            "values_and_beliefs",
            "dreams_and_goals",
            # Lessons 6-10: Society
            "news_and_media",
            "environment",
            "technology",
            "education",
            "health_and_fitness",
            # Lessons 11-15: Professional
            "job_interviews",
            "business_vocabulary",
            "presentations",
            "negotiations",
            "workplace_culture",
            # Lessons 16-20: Complex Situations
            "problem_solving",
            "giving_advice",
            "hypothetical_situations",
            "explaining_processes",
            "cause_and_effect",
            # Lessons 21-25: Culture
            "traditions_and_customs",
            "arts_and_literature",
            "history_basic",
            "current_events",
            "cultural_differences",
            # Lessons 26-30: Mastery
            "formal_vs_informal",
            "idioms_and_expressions",
            "review_abstract",
            "review_professional",
            "comprehensive_mastery",
        ],
    },
}

# Icelandic core vocabulary for A1 (~300 words for 30 lessons, ~10 words/lesson)
# Structure: (icelandic, english, type, phonetic)
ICELANDIC_CORE_VOCABULARY_A1 = [
    # Lesson 1: Greetings and farewells
    ("hæ", "hello", "greeting", "hai"),
    ("bless", "goodbye", "greeting", "bless"),
    ("góðan dag", "good day", "greeting", "GOH-than dahg"),
    ("góðan daginn", "good day (formal)", "greeting", "GOH-than DAH-gin"),
    ("gott kvöld", "good evening", "greeting", "goht kvuhld"),
    ("góða nótt", "good night", "greeting", "GOH-tha noht"),
    ("sæl", "hi (to female)", "greeting", "sail"),
    ("sæll", "hi (to male)", "greeting", "saitl"),
    ("vertu blessaður", "goodbye (to male)", "greeting", "VER-tu BLES-sa-thur"),
    ("vertu blessuð", "goodbye (to female)", "greeting", "VER-tu BLES-suth"),

    # Lesson 2: Basic courtesies
    ("takk", "thank you", "courtesy", "tahk"),
    ("takk fyrir", "thank you (for)", "courtesy", "tahk FIR-ir"),
    ("þakka þér fyrir", "thank you (formal)", "courtesy", "THAH-ka thyer FIR-ir"),
    ("gerðu svo vel", "you're welcome", "courtesy", "GYER-thu svo vel"),
    ("ekkert að þakka", "don't mention it", "courtesy", "EHK-ert ahth THAH-ka"),
    ("já", "yes", "response", "yow"),
    ("nei", "no", "response", "nay"),
    ("kannski", "maybe", "response", "KAHN-skee"),
    ("auðvitað", "of course", "response", "OITH-vi-tahth"),
    ("endilega", "please / by all means", "courtesy", "EN-di-le-ga"),

    # Lesson 3: Basic responses
    ("ég veit ekki", "I don't know", "phrase", "yeh vayt EH-kee"),
    ("afsakið", "excuse me", "courtesy", "AHF-sah-kith"),
    ("fyrirgefðu", "sorry", "courtesy", "FIR-ir-GYEV-thu"),
    ("það er í lagi", "it's okay", "phrase", "thahth er ee LAH-ee"),
    ("ekkert mál", "no problem", "phrase", "EHK-ert mowl"),
    ("góður", "good (m)", "adjective", "GOH-thur"),
    ("góð", "good (f)", "adjective", "gohth"),
    ("slæmt", "bad", "adjective", "slaimt"),
    ("frábært", "great", "adjective", "FROW-bairt"),
    ("allt í lagi", "all right", "phrase", "ahlt ee LAH-ee"),

    # Lesson 4: Yes/no and simple answers
    ("rétt", "right/correct", "adjective", "ryeht"),
    ("rangt", "wrong", "adjective", "rahngt"),
    ("jú", "yes (contradicting negative)", "response", "yoo"),
    ("alls ekki", "not at all", "phrase", "ahls EH-kee"),
    ("náttúrlega", "naturally", "adverb", "NOW-toor-le-ga"),
    ("samt", "still/anyway", "adverb", "sahmt"),
    ("líka", "also", "adverb", "LEE-ka"),
    ("bara", "just/only", "adverb", "BA-ra"),
    ("svo", "so/then", "adverb", "svoh"),
    ("mjög", "very", "adverb", "myuhg"),

    # Lesson 5: Introductions
    ("ég heiti", "my name is", "phrase", "yeh HAY-tee"),
    ("hvað heitir þú", "what is your name", "question", "kvath HAY-tir thoo"),
    ("ég er frá", "I am from", "phrase", "yeh er frow"),
    ("ég er íslenskur", "I am Icelandic (m)", "phrase", "yeh er EES-len-skur"),
    ("ég er íslensk", "I am Icelandic (f)", "phrase", "yeh er EES-lensk"),
    ("ég er bandarískur", "I am American (m)", "phrase", "yeh er ban-da-REE-skur"),
    ("ég er bandarísk", "I am American (f)", "phrase", "yeh er ban-da-REESK"),
    ("ánægður að kynnast þér", "pleased to meet you", "phrase", "OW-nyeg-thur ahth KIN-nahst thyer"),
    ("sömuleiðis", "likewise", "response", "SUH-mu-lay-this"),
    ("hvaðan ertu", "where are you from", "question", "KVA-than ER-tu"),

    # Lesson 6: Countries and nationalities
    ("Ísland", "Iceland", "noun", "EES-lahnd"),
    ("Bandaríkin", "United States", "noun", "ban-da-REE-kin"),
    ("Bretland", "Britain", "noun", "BREHT-lahnd"),
    ("Þýskaland", "Germany", "noun", "THEES-ka-lahnd"),
    ("Frakkland", "France", "noun", "FRAHK-lahnd"),
    ("Danmörk", "Denmark", "noun", "DAN-muhrk"),
    ("Noregur", "Norway", "noun", "NOR-e-gur"),
    ("Svíþjóð", "Sweden", "noun", "SVEE-thyohth"),
    ("land", "country", "noun", "lahnd"),
    ("þjóð", "nation", "noun", "thyohth"),

    # Lesson 7: Numbers 1-10
    ("einn", "one", "number", "aytn"),
    ("tveir", "two", "number", "tvair"),
    ("þrír", "three", "number", "threer"),
    ("fjórir", "four", "number", "FYOH-rir"),
    ("fimm", "five", "number", "fim"),
    ("sex", "six", "number", "seks"),
    ("sjö", "seven", "number", "syoh"),
    ("átta", "eight", "number", "OHT-ta"),
    ("níu", "nine", "number", "nee-u"),
    ("tíu", "ten", "number", "tee-u"),

    # Lesson 8: Questions - what, who
    ("hvað", "what", "question_word", "kvath"),
    ("hver", "who", "question_word", "kver"),
    ("hvað er þetta", "what is this", "question", "kvath er THET-ta"),
    ("hvað þýðir þetta", "what does this mean", "question", "kvath THEE-thir THET-ta"),
    ("hver er þetta", "who is this", "question", "kver er THET-ta"),
    ("hvað gerir þú", "what do you do", "question", "kvath GYE-rir thoo"),
    ("hvað viltu", "what do you want", "question", "kvath VIL-tu"),
    ("hvað kostar", "how much does it cost", "question", "kvath KOS-tar"),
    ("þetta", "this", "pronoun", "THET-ta"),
    ("það", "that/it", "pronoun", "thahth"),

    # Lesson 9: Questions - where, when, how
    ("hvar", "where", "question_word", "kvar"),
    ("hvenær", "when", "question_word", "KVEN-air"),
    ("hvernig", "how", "question_word", "KVER-nig"),
    ("hvers vegna", "why", "question_word", "KVERS VEG-na"),
    ("hvar ertu", "where are you", "question", "kvar ER-tu"),
    ("hvar er", "where is", "question", "kvar er"),
    ("hvenær kemur", "when does ... come", "question", "KVEN-air KE-mur"),
    ("hvernig hefurðu það", "how are you", "question", "KVER-nig HE-fur-thu thahth"),
    ("af hverju", "why (colloquial)", "question_word", "ahf KVER-yu"),
    ("hversu", "how (degree)", "question_word", "KVER-su"),

    # Lesson 10: Family members
    ("fjölskylda", "family", "noun", "FYUHL-skil-da"),
    ("mamma", "mother", "noun", "MAM-ma"),
    ("pabbi", "father", "noun", "PAB-bee"),
    ("foreldrar", "parents", "noun", "FOR-el-drar"),
    ("systir", "sister", "noun", "SIS-tir"),
    ("bróðir", "brother", "noun", "BROH-thir"),
    ("systkini", "siblings", "noun", "SIST-ki-ni"),
    ("afi", "grandfather", "noun", "AH-vi"),
    ("amma", "grandmother", "noun", "AM-ma"),
    ("frændi", "male cousin/uncle", "noun", "FRAIN-di"),

    # Lesson 11: More family
    ("frænka", "female cousin/aunt", "noun", "FRAINK-a"),
    ("barn", "child", "noun", "barn"),
    ("börn", "children", "noun", "buhrn"),
    ("eiginkona", "wife", "noun", "AY-gin-KO-na"),
    ("eiginmaður", "husband", "noun", "AY-gin-MAH-thur"),
    ("sonur", "son", "noun", "SOH-nur"),
    ("dóttir", "daughter", "noun", "DOHT-tir"),
    ("vinur", "friend (m)", "noun", "VI-nur"),
    ("vinkona", "friend (f)", "noun", "VIN-ko-na"),
    ("fólk", "people", "noun", "fohlk"),

    # Lesson 12: Common verbs (infinitive)
    ("að vera", "to be", "verb", "ahth VE-ra"),
    ("að hafa", "to have", "verb", "ahth HA-va"),
    ("að fara", "to go", "verb", "ahth FA-ra"),
    ("að koma", "to come", "verb", "ahth KO-ma"),
    ("að tala", "to speak", "verb", "ahth TA-la"),
    ("að skilja", "to understand", "verb", "ahth SKIL-ya"),
    ("að sjá", "to see", "verb", "ahth syow"),
    ("að heyra", "to hear", "verb", "ahth HAY-ra"),
    ("að vita", "to know (fact)", "verb", "ahth VI-ta"),
    ("að þekkja", "to know (person)", "verb", "ahth THEK-ya"),

    # Lesson 13: More verbs
    ("að borða", "to eat", "verb", "ahth BOR-tha"),
    ("að drekka", "to drink", "verb", "ahth DREK-ka"),
    ("að sofa", "to sleep", "verb", "ahth SO-va"),
    ("að vinna", "to work", "verb", "ahth VIN-na"),
    ("að búa", "to live", "verb", "ahth BOO-a"),
    ("að gera", "to do/make", "verb", "ahth GYE-ra"),
    ("að læra", "to learn", "verb", "ahth LAIR-a"),
    ("að lesa", "to read", "verb", "ahth LE-sa"),
    ("að skrifa", "to write", "verb", "ahth SKRI-va"),
    ("að spila", "to play", "verb", "ahth SPI-la"),

    # Lesson 14: Verb forms (present tense)
    ("ég er", "I am", "verb_form", "yeh er"),
    ("þú ert", "you are", "verb_form", "thoo ert"),
    ("hann er", "he is", "verb_form", "hahn er"),
    ("hún er", "she is", "verb_form", "hoon er"),
    ("við erum", "we are", "verb_form", "vith EH-rum"),
    ("ég hef", "I have", "verb_form", "yeh hev"),
    ("ég fer", "I go", "verb_form", "yeh fer"),
    ("ég kem", "I come", "verb_form", "yeh kem"),
    ("ég tala", "I speak", "verb_form", "yeh TA-la"),
    ("ég skil", "I understand", "verb_form", "yeh skil"),

    # Lesson 15: Places in city
    ("staður", "place", "noun", "STAH-thur"),
    ("borg", "city", "noun", "borg"),
    ("bær", "town", "noun", "bair"),
    ("heima", "home", "noun", "HAY-ma"),
    ("verslun", "store", "noun", "VERS-lun"),
    ("veitingahús", "restaurant", "noun", "VAY-ting-a-hoos"),
    ("hótel", "hotel", "noun", "HOH-tel"),
    ("flugvöllur", "airport", "noun", "FLUG-vuh-lur"),
    ("stöð", "station", "noun", "stuhth"),
    ("miðbær", "downtown", "noun", "MITH-bair"),

    # Lesson 16: More places and directions
    ("gata", "street", "noun", "GA-ta"),
    ("vegur", "road", "noun", "VE-gur"),
    ("sjúkrahús", "hospital", "noun", "SYOO-kra-hoos"),
    ("apótek", "pharmacy", "noun", "a-poh-TEK"),
    ("banki", "bank", "noun", "BAHN-ki"),
    ("pósthús", "post office", "noun", "POHST-hoos"),
    ("hægri", "right", "direction", "HAI-gri"),
    ("vinstri", "left", "direction", "VIN-stri"),
    ("beint áfram", "straight ahead", "direction", "baynt OW-fram"),
    ("nálægt", "near", "preposition", "NOW-laigt"),

    # Lesson 17: Food basics
    ("matur", "food", "noun", "MA-tur"),
    ("morgunmatur", "breakfast", "noun", "MOR-gun-ma-tur"),
    ("hádegismatur", "lunch", "noun", "HOW-day-gis-ma-tur"),
    ("kvöldmatur", "dinner", "noun", "KVUHLD-ma-tur"),
    ("brauð", "bread", "noun", "broith"),
    ("smjör", "butter", "noun", "smyuhr"),
    ("ostur", "cheese", "noun", "OS-tur"),
    ("egg", "egg", "noun", "ehg"),
    ("ávöxtur", "fruit", "noun", "OW-vuhks-tur"),
    ("grænmeti", "vegetables", "noun", "GRYN-me-tee"),

    # Lesson 18: Drinks and more food
    ("vatn", "water", "noun", "vahtn"),
    ("kaffi", "coffee", "noun", "KAF-fee"),
    ("te", "tea", "noun", "teh"),
    ("mjólk", "milk", "noun", "myohlk"),
    ("bjór", "beer", "noun", "byohr"),
    ("vín", "wine", "noun", "veen"),
    ("fiskur", "fish", "noun", "FIS-kur"),
    ("kjöt", "meat", "noun", "kyuht"),
    ("súpa", "soup", "noun", "SOO-pa"),
    ("salat", "salad", "noun", "sa-LAHT"),

    # Lesson 19: Time - parts of day
    ("tími", "time/hour", "noun", "TEE-mi"),
    ("klukkan", "the clock / o'clock", "noun", "KLUK-kan"),
    ("mínúta", "minute", "noun", "mee-NOO-ta"),
    ("sekúnda", "second", "noun", "se-KOON-da"),
    ("morgunn", "morning", "noun", "MOR-gun"),
    ("hádegi", "noon", "noun", "HOW-day-gi"),
    ("síðdegi", "afternoon", "noun", "SEETH-day-gi"),
    ("kvöld", "evening", "noun", "kvuhld"),
    ("nótt", "night", "noun", "noht"),
    ("klukkan er", "it is ... o'clock", "phrase", "KLUK-kan er"),

    # Lesson 20: Time expressions
    ("í dag", "today", "time", "ee dahg"),
    ("á morgun", "tomorrow", "time", "ow MOR-gun"),
    ("í gær", "yesterday", "time", "ee gair"),
    ("núna", "now", "time", "NOO-na"),
    ("seinna", "later", "time", "SAYT-na"),
    ("fljótlega", "soon", "time", "FLYOHT-le-ga"),
    ("dagur", "day", "noun", "DA-gur"),
    ("vika", "week", "noun", "VEE-ka"),
    ("mánuður", "month", "noun", "MOW-nu-thur"),
    ("ár", "year", "noun", "owr"),

    # Lesson 21: Days of week
    ("mánudagur", "Monday", "day", "MOW-nu-DA-gur"),
    ("þriðjudagur", "Tuesday", "day", "THRITH-yu-DA-gur"),
    ("miðvikudagur", "Wednesday", "day", "MITH-vi-ku-DA-gur"),
    ("fimmtudagur", "Thursday", "day", "FIM-tu-DA-gur"),
    ("föstudagur", "Friday", "day", "FUH-stu-DA-gur"),
    ("laugardagur", "Saturday", "day", "LOI-gar-DA-gur"),
    ("sunnudagur", "Sunday", "day", "SUN-nu-DA-gur"),
    ("virkur dagur", "weekday", "noun", "VIR-kur DA-gur"),
    ("helgi", "weekend", "noun", "HEL-gi"),
    ("hvað er dagurinn í dag", "what day is it today", "question", "kvath er DA-gur-in ee dahg"),

    # Lesson 22: Weather
    ("veður", "weather", "noun", "VE-thur"),
    ("sól", "sun", "noun", "sohl"),
    ("sólin skín", "the sun is shining", "phrase", "SOH-lin skeen"),
    ("rigning", "rain", "noun", "RIG-ning"),
    ("það rignir", "it's raining", "phrase", "thahth RIG-nir"),
    ("snjór", "snow", "noun", "snyohr"),
    ("það snjóar", "it's snowing", "phrase", "thahth SNYOH-ar"),
    ("vindur", "wind", "noun", "VIN-dur"),
    ("sky", "cloud", "noun", "ski"),
    ("skýjað", "cloudy", "adjective", "SKYY-yahth"),

    # Lesson 23: Temperature and weather adjectives
    ("kalt", "cold", "adjective", "kahlt"),
    ("heitt", "hot", "adjective", "hayt"),
    ("hlýtt", "warm", "adjective", "hlit"),
    ("svalt", "cool", "adjective", "svahlt"),
    ("gott veður", "good weather", "phrase", "goht VE-thur"),
    ("slæmt veður", "bad weather", "phrase", "slaimt VE-thur"),
    ("hiti", "temperature", "noun", "HI-ti"),
    ("gráður", "degrees", "noun", "GROW-thur"),
    ("þurrt", "dry", "adjective", "thurt"),
    ("blautt", "wet", "adjective", "bloyt"),

    # Lesson 24: Shopping
    ("að kaupa", "to buy", "verb", "ahth KOI-pa"),
    ("að borga", "to pay", "verb", "ahth BOR-ga"),
    ("peningur", "money", "noun", "PEN-ing-ur"),
    ("króna", "krona (currency)", "noun", "KROH-na"),
    ("verð", "price", "noun", "verth"),
    ("ódýrt", "cheap", "adjective", "OH-deert"),
    ("dýrt", "expensive", "adjective", "deert"),
    ("stórt", "big", "adjective", "stohrt"),
    ("lítið", "small", "adjective", "LEE-tith"),
    ("afsláttur", "discount", "noun", "AHF-slowt-ur"),

    # Lesson 25: Colors
    ("litur", "color", "noun", "LI-tur"),
    ("rauður", "red", "adjective", "ROI-thur"),
    ("blár", "blue", "adjective", "blow-r"),
    ("grænn", "green", "adjective", "graitn"),
    ("gulur", "yellow", "adjective", "GU-lur"),
    ("svartur", "black", "adjective", "SVAR-tur"),
    ("hvítur", "white", "adjective", "KVEE-tur"),
    ("brúnn", "brown", "adjective", "broon"),
    ("grár", "gray", "adjective", "growr"),
    ("appelsínugulur", "orange", "adjective", "ah-pel-SEE-nu-gu-lur"),

    # Lesson 26: Daily routines
    ("að vakna", "to wake up", "verb", "ahth VAHK-na"),
    ("að fara á fætur", "to get up", "verb", "ahth FA-ra ow FAI-tur"),
    ("að klæða sig", "to get dressed", "verb", "ahth KLAI-tha sig"),
    ("að borsta tennur", "to brush teeth", "verb", "ahth BOR-sta TEN-ur"),
    ("að þvo sér", "to wash oneself", "verb", "ahth thvoh syer"),
    ("að fara í vinnuna", "to go to work", "verb", "ahth FA-ra ee VIN-una"),
    ("að koma heim", "to come home", "verb", "ahth KO-ma haym"),
    ("að fara að sofa", "to go to sleep", "verb", "ahth FA-ra ahth SO-va"),
    ("á hverjum degi", "every day", "phrase", "ow KVER-yum DAY-gi"),
    ("alltaf", "always", "adverb", "AHL-tahv"),

    # Lesson 27: Likes and dislikes
    ("að vilja", "to want", "verb", "ahth VIL-ya"),
    ("ég vil", "I want", "phrase", "yeh vil"),
    ("að þykja vænt um", "to like/love", "verb", "ahth THEE-kya vaint um"),
    ("mér finnst", "I think/find", "phrase", "myer finst"),
    ("mér líkar", "I like", "phrase", "myer LEE-kar"),
    ("mér líkar ekki", "I don't like", "phrase", "myer LEE-kar EH-kee"),
    ("ég elska", "I love", "phrase", "yeh EL-ska"),
    ("ég hata", "I hate", "phrase", "yeh HA-ta"),
    ("uppáhald", "favorite", "noun", "UP-ow-hahld"),
    ("besta", "best", "adjective", "BES-ta"),

    # Lesson 28: Abilities - can/must
    ("að geta", "to be able to", "verb", "ahth GYE-ta"),
    ("ég get", "I can", "phrase", "yeh gyet"),
    ("ég get ekki", "I cannot", "phrase", "yeh gyet EH-kee"),
    ("að mega", "may/to be allowed", "verb", "ahth ME-ga"),
    ("má ég", "may I", "phrase", "mow yeh"),
    ("að þurfa", "to need/must", "verb", "ahth THUR-va"),
    ("ég þarf", "I need", "phrase", "yeh tharf"),
    ("að verða", "to have to/become", "verb", "ahth VERTH-a"),
    ("ég verð", "I must/have to", "phrase", "yeh verth"),
    ("auðvelt", "easy", "adjective", "OITH-velt"),

    # Lesson 29: Polite expressions and needs
    ("má ég fá", "may I have", "phrase", "mow yeh fow"),
    ("viltu", "do you want", "question", "VIL-tu"),
    ("vinsamlegast", "please (formal)", "adverb", "VIN-sahm-le-gahst"),
    ("hjálp", "help", "noun", "hyowlp"),
    ("að hjálpa", "to help", "verb", "ahth HYOWL-pa"),
    ("geturðu hjálpað mér", "can you help me", "question", "GYE-tur-thu HYOWL-pahth myer"),
    ("vandamál", "problem", "noun", "VAN-da-mowl"),
    ("lausn", "solution", "noun", "loisn"),
    ("erfitt", "difficult", "adjective", "ER-fit"),
    ("hægt", "slow/possible", "adjective", "haigt"),

    # Lesson 30: Travel and comprehensive phrases
    ("ferð", "trip/journey", "noun", "ferth"),
    ("ferðalag", "travel", "noun", "FER-tha-lahg"),
    ("flug", "flight", "noun", "flug"),
    ("miði", "ticket", "noun", "MI-thi"),
    ("vegabréf", "passport", "noun", "VE-ga-bryef"),
    ("ég tala ekki íslensku", "I don't speak Icelandic", "phrase", "yeh TA-la EH-kee EES-len-sku"),
    ("talarðu ensku", "do you speak English", "question", "TA-lar-thu EN-sku"),
    ("ég skil ekki", "I don't understand", "phrase", "yeh skil EH-kee"),
    ("geturðu endurtekið", "can you repeat", "question", "GYE-tur-thu EN-dur-te-kith"),
    ("smávegis", "a little", "adverb", "SMOW-ve-gis"),
]

# Icelandic core vocabulary for A2 (~450 words for 30 lessons, ~15 words/lesson)
# Builds on A1, introduces past tense, more complex phrases
ICELANDIC_CORE_VOCABULARY_A2 = [
    # Lesson 1: Numbers 11-100
    ("ellefu", "eleven", "number", "EHL-e-vu"),
    ("tólf", "twelve", "number", "tohlv"),
    ("þrettán", "thirteen", "number", "THREH-town"),
    ("fjórtán", "fourteen", "number", "FYOHR-town"),
    ("fimmtán", "fifteen", "number", "FIM-town"),
    ("sextán", "sixteen", "number", "SEKS-town"),
    ("sautján", "seventeen", "number", "SOI-town"),
    ("átján", "eighteen", "number", "OWT-town"),
    ("nítján", "nineteen", "number", "NEET-town"),
    ("tuttugu", "twenty", "number", "TU-tu-gu"),
    ("þrjátíu", "thirty", "number", "THRYOW-tee-u"),
    ("fjörutíu", "forty", "number", "FYUH-ru-tee-u"),
    ("fimmtíu", "fifty", "number", "FIM-tee-u"),
    ("sextíu", "sixty", "number", "SEKS-tee-u"),
    ("hundrað", "hundred", "number", "HUN-drath"),

    # Lesson 2: Months and dates
    ("janúar", "January", "month", "YA-noo-ar"),
    ("febrúar", "February", "month", "FEB-roo-ar"),
    ("mars", "March", "month", "mars"),
    ("apríl", "April", "month", "a-PREEL"),
    ("maí", "May", "month", "mai"),
    ("júní", "June", "month", "YOO-nee"),
    ("júlí", "July", "month", "YOO-lee"),
    ("ágúst", "August", "month", "OW-goost"),
    ("september", "September", "month", "sep-TEM-ber"),
    ("október", "October", "month", "ok-TOH-ber"),
    ("nóvember", "November", "month", "noh-VEM-ber"),
    ("desember", "December", "month", "de-SEM-ber"),
    ("dagsetning", "date", "noun", "DAG-set-ning"),
    ("fæðingardagur", "birthday", "noun", "FAI-thing-ar-DA-gur"),
    ("hvaða dagsetning", "what date", "question", "KVA-tha DAG-set-ning"),

    # Lesson 3: Describing people - appearance
    ("hár", "tall", "adjective", "howr"),
    ("lágur", "short (height)", "adjective", "LOW-gur"),
    ("þunnur", "thin", "adjective", "THUN-ur"),
    ("þykkur", "thick/fat", "adjective", "THIK-ur"),
    ("fallegur", "beautiful (m)", "adjective", "FAHL-e-gur"),
    ("falleg", "beautiful (f)", "adjective", "FAHL-eg"),
    ("myndarlegur", "handsome", "adjective", "MIN-dar-le-gur"),
    ("ungur", "young", "adjective", "UN-gur"),
    ("gamall", "old", "adjective", "GA-mahtl"),
    ("sterkur", "strong", "adjective", "STERK-ur"),
    ("veikur", "weak", "adjective", "VAYK-ur"),
    ("hár", "hair", "noun", "howr"),
    ("augu", "eyes", "noun", "OI-gu"),
    ("andlit", "face", "noun", "AHND-lit"),
    ("útlit", "appearance", "noun", "OOT-lit"),

    # Lesson 4: Describing places
    ("stór", "large", "adjective", "stohr"),
    ("lítill", "small", "adjective", "LEE-titl"),
    ("gamaldags", "old-fashioned", "adjective", "GA-mal-dags"),
    ("nútímalegur", "modern", "adjective", "NOO-tee-ma-le-gur"),
    ("fallegur staður", "beautiful place", "phrase", "FAHL-e-gur STAH-thur"),
    ("hreinn", "clean", "adjective", "hraytn"),
    ("óhreinn", "dirty", "adjective", "OH-hraytn"),
    ("þægilegur", "comfortable", "adjective", "THAI-gi-le-gur"),
    ("rólugur", "calm/quiet", "adjective", "ROH-lu-gur"),
    ("hávaðasamur", "noisy", "adjective", "HOW-va-tha-sa-mur"),
    ("fjarlægur", "far/distant", "adjective", "FYAR-lai-gur"),
    ("nálægur", "nearby", "adjective", "NOW-lai-gur"),
    ("þéttbýli", "urban area", "noun", "THYEHT-bee-li"),
    ("sveit", "countryside", "noun", "svayt"),
    ("náttúra", "nature", "noun", "NOW-too-ra"),

    # Lesson 5: Describing things
    ("nýr", "new", "adjective", "neer"),
    ("gamall", "old (things)", "adjective", "GA-mahtl"),
    ("góður", "good", "adjective", "GOH-thur"),
    ("vondur", "bad", "adjective", "VON-dur"),
    ("harður", "hard", "adjective", "HAR-thur"),
    ("mjúkur", "soft", "adjective", "MYOO-kur"),
    ("létt", "light (weight)", "adjective", "lyeht"),
    ("þungur", "heavy", "adjective", "THUNG-ur"),
    ("fljótur", "fast", "adjective", "FLYOH-tur"),
    ("hægur", "slow", "adjective", "HAI-gur"),
    ("fullur", "full", "adjective", "FUL-ur"),
    ("tómur", "empty", "adjective", "TOH-mur"),
    ("opinn", "open", "adjective", "OH-pin"),
    ("lokaður", "closed", "adjective", "LOH-ka-thur"),
    ("brotinn", "broken", "adjective", "BROH-tin"),

    # Lesson 6: Hobbies and sports
    ("áhugamál", "hobby", "noun", "OW-hu-ga-mowl"),
    ("íþrótt", "sport", "noun", "EE-throht"),
    ("fótbolti", "football/soccer", "noun", "FOHT-bol-ti"),
    ("körfubolti", "basketball", "noun", "KUHR-fu-bol-ti"),
    ("sund", "swimming", "noun", "sund"),
    ("að synda", "to swim", "verb", "ahth SIN-da"),
    ("að hlaupa", "to run", "verb", "ahth HLOI-pa"),
    ("að hjóla", "to cycle", "verb", "ahth HYOH-la"),
    ("að skíða", "to ski", "verb", "ahth SKEE-tha"),
    ("að ganga", "to walk", "verb", "ahth GAHNG-a"),
    ("tónlist", "music", "noun", "TOHN-list"),
    ("að hlusta á", "to listen to", "verb", "ahth HLUS-ta ow"),
    ("lestur", "reading", "noun", "LES-tur"),
    ("að elda", "to cook", "verb", "ahth EL-da"),
    ("garðyrkja", "gardening", "noun", "GARTH-ir-kya"),

    # Lesson 7: Entertainment
    ("kvikmynd", "movie", "noun", "KVIK-mind"),
    ("bíó", "cinema", "noun", "BEE-oh"),
    ("leikhús", "theater", "noun", "LAYK-hoos"),
    ("sýning", "show/exhibition", "noun", "SEE-ning"),
    ("tónleikar", "concert", "noun", "TOHN-lay-kar"),
    ("sjónvarp", "television", "noun", "SYOHN-varp"),
    ("útvarp", "radio", "noun", "OOT-varp"),
    ("bók", "book", "noun", "bohk"),
    ("tímarit", "magazine", "noun", "TEE-ma-rit"),
    ("dagblað", "newspaper", "noun", "DAG-blahth"),
    ("leikur", "game", "noun", "LAY-kur"),
    ("veisla", "party", "noun", "VAYS-la"),
    ("skemmtun", "entertainment", "noun", "SKEMT-un"),
    ("að horfa á", "to watch", "verb", "ahth HOR-va ow"),
    ("að njóta", "to enjoy", "verb", "ahth NYOH-ta"),

    # Lesson 8: Weekend activities
    ("um helgina", "on the weekend", "phrase", "um HEL-gi-na"),
    ("á laugardögum", "on Saturdays", "phrase", "ow LOI-gar-DUH-gum"),
    ("frí", "free time/vacation", "noun", "free"),
    ("hvíldardag", "day off", "noun", "KVIL-dar-dag"),
    ("að slaka á", "to relax", "verb", "ahth SLAH-ka ow"),
    ("að hitta vini", "to meet friends", "verb", "ahth HIT-ta VI-ni"),
    ("að fara út", "to go out", "verb", "ahth FA-ra oot"),
    ("að vera heima", "to stay home", "verb", "ahth VE-ra HAY-ma"),
    ("að sofa lengi", "to sleep in", "verb", "ahth SO-va LEN-gi"),
    ("útivera", "outdoor activity", "noun", "OO-ti-ve-ra"),
    ("að ferðast", "to travel", "verb", "ahth FER-thast"),
    ("að heimsækja", "to visit", "verb", "ahth HAYM-sai-kya"),
    ("skemmtilegur", "fun/enjoyable", "adjective", "SKEMT-i-le-gur"),
    ("leiðinlegur", "boring", "adjective", "LAY-thin-le-gur"),
    ("spennandi", "exciting", "adjective", "SPEN-an-di"),

    # Lesson 9: Holidays
    ("frídagur", "holiday", "noun", "FREE-da-gur"),
    ("jól", "Christmas", "noun", "yohl"),
    ("gleðileg jól", "merry Christmas", "phrase", "GLAY-thi-leg yohl"),
    ("páskar", "Easter", "noun", "POW-skar"),
    ("nýár", "New Year", "noun", "NEE-owr"),
    ("þjóðhátíð", "national holiday", "noun", "THYOHTH-how-teeth"),
    ("afmæli", "birthday/anniversary", "noun", "AHV-mai-li"),
    ("til hamingju", "congratulations", "phrase", "til HA-ming-yu"),
    ("gjöf", "gift", "noun", "gyuhv"),
    ("að gefa", "to give", "verb", "ahth GYE-va"),
    ("að fá", "to receive/get", "verb", "ahth fow"),
    ("hátíð", "festival", "noun", "HOW-teeth"),
    ("sumardagurinn fyrsti", "first day of summer", "noun", "SU-mar-DA-gur-in FIR-sti"),
    ("þorrablót", "midwinter feast", "noun", "THOR-a-bloht"),
    ("verslunarmannahelgi", "commerce weekend", "noun", "VERS-lu-nar-MAN-a-HEL-gi"),

    # Lesson 10: Celebrations
    ("að halda upp á", "to celebrate", "verb", "ahth HAL-da up ow"),
    ("veisla", "celebration/party", "noun", "VAYS-la"),
    ("brúðkaup", "wedding", "noun", "BROOTH-koip"),
    ("fermingu", "confirmation", "noun", "FER-ming-u"),
    ("útskrift", "graduation", "noun", "OOT-skrift"),
    ("kaka", "cake", "noun", "KA-ka"),
    ("kerti", "candle", "noun", "KER-ti"),
    ("blóm", "flowers", "noun", "blohm"),
    ("að óska", "to wish", "verb", "ahth OH-ska"),
    ("gangi þér vel", "good luck", "phrase", "GAHNG-i thyer vel"),
    ("innbýðandi", "host", "noun", "IN-bee-than-di"),
    ("gestur", "guest", "noun", "GES-tur"),
    ("að skemmta sér", "to have fun", "verb", "ahth SKEMT-a syer"),
    ("minningarverður", "memorable", "adjective", "MIN-ing-ar-ver-thur"),
    ("hefð", "tradition", "noun", "hevth"),

    # Lesson 11: At the doctor
    ("læknir", "doctor", "noun", "LAIK-nir"),
    ("hjúkrunarfræðingur", "nurse", "noun", "HYOOK-ru-nar-FRAI-thing-ur"),
    ("sjúklingur", "patient", "noun", "SYOOK-ling-ur"),
    ("heilsugæsla", "health center", "noun", "HAYL-su-gais-la"),
    ("að vera veikur", "to be sick", "phrase", "ahth VE-ra VAY-kur"),
    ("verkur", "pain", "noun", "VER-kur"),
    ("höfuðverkur", "headache", "noun", "HUH-vuth-ver-kur"),
    ("hiti", "fever", "noun", "HI-ti"),
    ("kvef", "cold (illness)", "noun", "kvev"),
    ("að hósta", "to cough", "verb", "ahth HOH-sta"),
    ("að hnerra", "to sneeze", "verb", "ahth HNER-a"),
    ("lyf", "medicine", "noun", "liv"),
    ("lyfseðill", "prescription", "noun", "LIV-se-thitl"),
    ("tími hjá lækni", "doctor's appointment", "phrase", "TEE-mi hyow LAIK-ni"),
    ("að batna", "to get better", "verb", "ahth BAHT-na"),

    # Lesson 12: At the pharmacy
    ("apótek", "pharmacy", "noun", "a-POH-tek"),
    ("lyfjafræðingur", "pharmacist", "noun", "LIV-ya-FRAI-thing-ur"),
    ("verkjalyf", "painkiller", "noun", "VER-kya-liv"),
    ("sýklalyf", "antibiotic", "noun", "SEE-kla-liv"),
    ("húðkrem", "skin cream", "noun", "HOOTH-krem"),
    ("plástur", "bandage/plaster", "noun", "PLOW-stur"),
    ("hitalækkandi", "fever reducer", "noun", "HI-ta-LAIK-an-di"),
    ("vítamín", "vitamins", "noun", "VEE-ta-meen"),
    ("aukaverkun", "side effect", "noun", "OI-ka-ver-kun"),
    ("skammtur", "dose", "noun", "SKAHM-tur"),
    ("að taka inn", "to take (medicine)", "verb", "ahth TA-ka in"),
    ("uppskrift", "recipe/prescription", "noun", "UP-skrift"),
    ("ofnæmi", "allergy", "noun", "OV-nai-mi"),
    ("einkenni", "symptom", "noun", "AYN-ken-ni"),
    ("meðferð", "treatment", "noun", "METH-ferth"),

    # Lesson 13: At the bank
    ("banki", "bank", "noun", "BAHN-ki"),
    ("bankareikningur", "bank account", "noun", "BAHN-ka-RAYK-ning-ur"),
    ("debetkort", "debit card", "noun", "de-BET-kort"),
    ("kreditkort", "credit card", "noun", "kre-DIT-kort"),
    ("reiðufé", "cash", "noun", "RAY-thu-fyeh"),
    ("að leggja inn", "to deposit", "verb", "ahth LEG-ya in"),
    ("að taka út", "to withdraw", "verb", "ahth TA-ka oot"),
    ("millifærsla", "transfer", "noun", "MIL-i-fairs-la"),
    ("vextir", "interest", "noun", "VEKS-tir"),
    ("lán", "loan", "noun", "lown"),
    ("reikningur", "bill/account", "noun", "RAYK-ning-ur"),
    ("gjaldmiðill", "currency", "noun", "GYAHLD-mi-thitl"),
    ("gengi", "exchange rate", "noun", "GENG-i"),
    ("hraðbanki", "ATM", "noun", "HRATH-bahn-ki"),
    ("að greiða", "to pay", "verb", "ahth GRAY-tha"),

    # Lesson 14: At the post office
    ("pósthús", "post office", "noun", "POHST-hoos"),
    ("bréf", "letter", "noun", "bryev"),
    ("póstkort", "postcard", "noun", "POHST-kort"),
    ("pakki", "package", "noun", "PAHK-i"),
    ("frímerki", "stamp", "noun", "FREE-mer-ki"),
    ("að senda", "to send", "verb", "ahth SEN-da"),
    ("að fá sent", "to receive (mail)", "verb", "ahth fow sent"),
    ("heimilisfang", "address", "noun", "HAY-mi-lis-fahng"),
    ("póstnúmer", "postal code", "noun", "POHST-noo-mer"),
    ("móttakandi", "recipient", "noun", "MOHT-ta-kahn-di"),
    ("sendandi", "sender", "noun", "SEN-dahn-di"),
    ("þyngd", "weight", "noun", "thingth"),
    ("burðargjald", "postage", "noun", "BUR-thar-gyahld"),
    ("flýtipóstur", "express mail", "noun", "FLEE-ti-pohs-tur"),
    ("ábyrgðarpóstur", "registered mail", "noun", "OW-bir-thar-pohs-tur"),

    # Lesson 15: Public transport
    ("almenningssamgöngur", "public transport", "noun", "AHL-men-ings-sahm-GUHN-gur"),
    ("strætisvagn", "bus", "noun", "STRAI-tis-vahgn"),
    ("biðstöð", "bus stop", "noun", "BITH-stuhth"),
    ("leið", "route", "noun", "layth"),
    ("tímatafla", "timetable", "noun", "TEE-ma-TAHF-la"),
    ("miði", "ticket", "noun", "MI-thi"),
    ("mánaðarkort", "monthly pass", "noun", "MOW-na-thar-kort"),
    ("fargjald", "fare", "noun", "FAR-gyahld"),
    ("næsta stöð", "next stop", "phrase", "NAIS-ta stuhth"),
    ("endastöð", "terminal", "noun", "EN-da-stuhth"),
    ("að stíga upp", "to get on", "verb", "ahth STEE-ga up"),
    ("að stíga af", "to get off", "verb", "ahth STEE-ga ahv"),
    ("ökumaður", "driver", "noun", "UH-ku-MA-thur"),
    ("farþegi", "passenger", "noun", "FAR-the-gi"),
    ("seinkun", "delay", "noun", "SAYN-kun"),

    # Lesson 16: Rooms and furniture
    ("herbergi", "room", "noun", "HER-ber-gi"),
    ("eldhús", "kitchen", "noun", "ELD-hoos"),
    ("stofa", "living room", "noun", "STO-va"),
    ("svefnherbergi", "bedroom", "noun", "SVEV-n-her-ber-gi"),
    ("baðherbergi", "bathroom", "noun", "BAHTH-her-ber-gi"),
    ("borðstofa", "dining room", "noun", "BORTH-sto-va"),
    ("sófi", "sofa", "noun", "SOH-vi"),
    ("stóll", "chair", "noun", "stohtl"),
    ("borð", "table", "noun", "borth"),
    ("rúm", "bed", "noun", "room"),
    ("skápur", "closet/cabinet", "noun", "SKOW-pur"),
    ("hillur", "shelves", "noun", "HIL-ur"),
    ("lampi", "lamp", "noun", "LAHM-pi"),
    ("teppi", "carpet/rug", "noun", "TEP-i"),
    ("gluggi", "window", "noun", "GLUG-i"),

    # Lesson 17: Household chores
    ("heimilisstörf", "housework", "noun", "HAY-mi-lis-STUHR-v"),
    ("að þrífa", "to clean", "verb", "ahth THREE-va"),
    ("að ryksuga", "to vacuum", "verb", "ahth RIK-su-ga"),
    ("að þvo upp", "to wash dishes", "verb", "ahth thvoh up"),
    ("að þvo þvott", "to do laundry", "verb", "ahth thvoh thvoht"),
    ("að strauja", "to iron", "verb", "ahth STROI-ya"),
    ("að elda mat", "to cook food", "verb", "ahth EL-da maht"),
    ("að búa til", "to make/prepare", "verb", "ahth BOO-a til"),
    ("að gera við", "to repair", "verb", "ahth GYE-ra vith"),
    ("þvottavél", "washing machine", "noun", "THVOT-a-vyel"),
    ("uppþvottavél", "dishwasher", "noun", "UP-thvot-a-vyel"),
    ("ryksuga", "vacuum cleaner", "noun", "RIK-su-ga"),
    ("sópi", "broom", "noun", "SOH-pi"),
    ("rusl", "garbage", "noun", "rusl"),
    ("endurvinnsla", "recycling", "noun", "EN-dur-VIN-sla"),

    # Lesson 18: Workplace vocabulary
    ("vinnustaður", "workplace", "noun", "VIN-u-STAH-thur"),
    ("skrifstofa", "office", "noun", "SKRIV-sto-va"),
    ("fundur", "meeting", "noun", "FUN-dur"),
    ("verkefni", "project/task", "noun", "VER-kev-ni"),
    ("frestur", "deadline", "noun", "FRES-tur"),
    ("launin", "salary", "noun", "LOI-nin"),
    ("yfirmaður", "boss/supervisor", "noun", "I-vir-MA-thur"),
    ("samstarfsmaður", "colleague", "noun", "SAHM-starfs-MA-thur"),
    ("viðskiptavinur", "client/customer", "noun", "VITH-skip-ta-VI-nur"),
    ("að sækja um", "to apply for", "verb", "ahth SAI-kya um"),
    ("starfsumsókn", "job application", "noun", "STARFS-um-SOHKN"),
    ("ferilskrá", "CV/resume", "noun", "FE-ril-skrow"),
    ("viðtal", "interview", "noun", "VITH-tahl"),
    ("starf", "job/position", "noun", "stahrf"),
    ("atvinnulaus", "unemployed", "adjective", "AHT-vin-u-lois"),

    # Lesson 19: Colleagues and meetings
    ("teymi", "team", "noun", "TAY-mi"),
    ("deild", "department", "noun", "dayld"),
    ("fundarherbergi", "meeting room", "noun", "FUN-dar-HER-ber-gi"),
    ("dagskrá", "agenda", "noun", "DAG-skrow"),
    ("tillaga", "proposal", "noun", "TIL-a-ga"),
    ("ákvörðun", "decision", "noun", "OWK-vuhr-thun"),
    ("samkomulag", "agreement", "noun", "SAHM-ko-mu-lahg"),
    ("að ræða", "to discuss", "verb", "ahth RAI-tha"),
    ("að kynna", "to present", "verb", "ahth KIN-a"),
    ("að samþykkja", "to approve", "verb", "ahth SAHM-thik-ya"),
    ("að hafna", "to reject", "verb", "ahth HAHV-na"),
    ("tölvupóstur", "email", "noun", "TUHL-vu-POHS-tur"),
    ("skjal", "document", "noun", "skyahl"),
    ("skýrsla", "report", "noun", "SKEER-sla"),
    ("kynning", "presentation", "noun", "KIN-ing"),

    # Lesson 20: Schedules
    ("áætlun", "schedule/plan", "noun", "OW-ayt-lun"),
    ("dagatal", "calendar", "noun", "DA-ga-tahl"),
    ("tímasetning", "timing", "noun", "TEE-ma-SET-ning"),
    ("ráðstefna", "conference", "noun", "ROWTHS-TEV-na"),
    ("skipulagður", "organized", "adjective", "SKI-pu-lahg-thur"),
    ("annasamt", "busy (schedule)", "adjective", "AHN-a-sahmt"),
    ("laust", "available/free", "adjective", "loist"),
    ("frátekið", "reserved/booked", "adjective", "FROW-te-kith"),
    ("að bóka", "to book/reserve", "verb", "ahth BOH-ka"),
    ("að aflýsa", "to cancel", "verb", "ahth AHV-lee-sa"),
    ("að fresta", "to postpone", "verb", "ahth FRES-ta"),
    ("að mæta", "to attend/show up", "verb", "ahth MAI-ta"),
    ("tímaáætlun", "timetable", "noun", "TEE-ma-OW-ayt-lun"),
    ("vinna yfirvinnu", "to work overtime", "phrase", "VIN-a I-vir-VIN-u"),
    ("hlé", "break/pause", "noun", "hlyeh"),

    # Lesson 21: Opinions and preferences
    ("álit", "opinion", "noun", "OW-lit"),
    ("skoðun", "view/opinion", "noun", "SKO-thun"),
    ("að halda", "to think/believe", "verb", "ahth HAHL-da"),
    ("ég held", "I think", "phrase", "yeh held"),
    ("mér finnst", "I find/think", "phrase", "myer finst"),
    ("að vera sammála", "to agree", "phrase", "ahth VE-ra SAHM-mow-la"),
    ("að vera ósammála", "to disagree", "phrase", "ahth VE-ra OH-sahm-mow-la"),
    ("frekar", "rather/prefer", "adverb", "FRE-kar"),
    ("helst", "preferably", "adverb", "helst"),
    ("eins og", "like/as", "conjunction", "ayns ohg"),
    ("að mínu mati", "in my opinion", "phrase", "ahth MEE-nu MA-ti"),
    ("rétt eða rangt", "right or wrong", "phrase", "ryeht e-tha rahngt"),
    ("sannfærandi", "convincing", "adjective", "SAHN-FAIR-ahn-di"),
    ("áhugaverður", "interesting", "adjective", "OW-hu-ga-VER-thur"),
    ("mikilvægur", "important", "adjective", "MI-kil-VAI-gur"),

    # Lesson 22: Making plans
    ("áform", "plan/intention", "noun", "OW-form"),
    ("að ætla", "to intend/plan", "verb", "ahth AIT-la"),
    ("ég ætla að", "I'm going to", "phrase", "yeh AIT-la ahth"),
    ("að skipuleggja", "to plan/organize", "verb", "ahth SKI-pu-LEG-ya"),
    ("tillaga", "suggestion", "noun", "TIL-a-ga"),
    ("hugmynd", "idea", "noun", "HUG-mind"),
    ("hvað segirðu", "what do you say", "question", "kvath SE-gir-thu"),
    ("hittumst", "let's meet", "phrase", "HIT-umst"),
    ("kl. átta", "at 8 o'clock", "phrase", "kluk-an OHT-ta"),
    ("á morgun", "tomorrow", "time", "ow MOR-gun"),
    ("í næstu viku", "next week", "phrase", "ee NAIS-tu VI-ku"),
    ("í kvöld", "tonight", "phrase", "ee kvuhld"),
    ("á föstudagskvöld", "on Friday night", "phrase", "ow FUHS-tu-dags-kvuhld"),
    ("að lofa", "to promise", "verb", "ahth LO-va"),
    ("ef", "if", "conjunction", "ev"),

    # Lesson 23: Giving directions
    ("átt", "direction", "noun", "owt"),
    ("norður", "north", "noun", "NOR-thur"),
    ("suður", "south", "noun", "SU-thur"),
    ("austur", "east", "noun", "OIS-tur"),
    ("vestur", "west", "noun", "VES-tur"),
    ("beygja til hægri", "turn right", "phrase", "BAY-gya til HAI-gri"),
    ("beygja til vinstri", "turn left", "phrase", "BAY-gya til VIN-stri"),
    ("halda áfram", "continue straight", "phrase", "HAHL-da OW-fram"),
    ("yfir", "over/across", "preposition", "I-vir"),
    ("hjá", "by/past", "preposition", "hyow"),
    ("fyrir framan", "in front of", "preposition", "FI-rir FRA-man"),
    ("fyrir aftan", "behind", "preposition", "FI-rir AHF-tahn"),
    ("á milli", "between", "preposition", "ow MIL-a"),
    ("við hliðina á", "next to", "preposition", "vith HLITH-i-na ow"),
    ("á horninu", "at the corner", "phrase", "ow HOR-ni-nu"),

    # Lesson 24: Complaints and requests
    ("kvörtun", "complaint", "noun", "KVUHR-tun"),
    ("beiðni", "request", "noun", "BAYTH-ni"),
    ("að kvarta", "to complain", "verb", "ahth KVAR-ta"),
    ("að biðja um", "to ask for", "verb", "ahth BITH-ya um"),
    ("vandamál", "problem", "noun", "VAN-da-mowl"),
    ("bilun", "malfunction", "noun", "BI-lun"),
    ("þetta virkar ekki", "this doesn't work", "phrase", "THET-ta VIR-kar EH-kee"),
    ("gætirðu", "could you", "question", "GAI-tir-thu"),
    ("væri hægt að", "would it be possible to", "phrase", "VAI-ri haigt ahth"),
    ("endurgreiðsla", "refund", "noun", "EN-dur-GRAYTHS-la"),
    ("að skipta um", "to exchange", "verb", "ahth SKIP-ta um"),
    ("að laga", "to fix", "verb", "ahth LA-ga"),
    ("þjónusta", "service", "noun", "THYOH-nus-ta"),
    ("afsökun", "apology", "noun", "AHV-suh-kun"),
    ("úrlausn", "solution", "noun", "OOR-loisn"),

    # Lesson 25: Comparisons
    ("samanburður", "comparison", "noun", "SA-mahn-BUR-thur"),
    ("stærri", "bigger", "adjective", "STAIR-i"),
    ("minni", "smaller", "adjective", "MIN-i"),
    ("betri", "better", "adjective", "BET-ri"),
    ("verri", "worse", "adjective", "VER-i"),
    ("eldri", "older", "adjective", "EL-dri"),
    ("yngri", "younger", "adjective", "ING-ri"),
    ("dýrari", "more expensive", "adjective", "DEE-ra-ri"),
    ("ódýrari", "cheaper", "adjective", "OH-dee-ra-ri"),
    ("hraðari", "faster", "adjective", "HRATH-a-ri"),
    ("hægari", "slower", "adjective", "HAI-ga-ri"),
    ("eins og", "same as", "conjunction", "ayns ohg"),
    ("ólíkt", "unlike", "adverb", "OH-leekt"),
    ("meira", "more", "adverb", "MAY-ra"),
    ("minna", "less", "adverb", "MIN-a"),

    # Lesson 26: Storytelling - past tense
    ("í gær", "yesterday", "time", "ee gair"),
    ("fyrir viku síðan", "a week ago", "phrase", "FI-rir VI-ku SEE-than"),
    ("ég fór", "I went", "verb_form", "yeh fohr"),
    ("ég kom", "I came", "verb_form", "yeh kohm"),
    ("ég sá", "I saw", "verb_form", "yeh sow"),
    ("ég gerði", "I did/made", "verb_form", "yeh GYER-thi"),
    ("ég sagði", "I said", "verb_form", "yeh SAG-thi"),
    ("ég var", "I was", "verb_form", "yeh var"),
    ("það var", "there was", "phrase", "thahth var"),
    ("þegar", "when (past)", "conjunction", "THE-gar"),
    ("áður en", "before", "conjunction", "OW-thur en"),
    ("eftir að", "after", "conjunction", "EV-tir ahth"),
    ("saga", "story", "noun", "SA-ga"),
    ("að segja frá", "to tell about", "verb", "ahth SEG-ya frow"),
    ("minnast", "to remember", "verb", "MIN-ast"),

    # Lesson 27: Future plans
    ("framtíð", "future", "noun", "FRAHM-teeth"),
    ("ég mun", "I will", "phrase", "yeh mun"),
    ("ég ætla að", "I'm going to", "phrase", "yeh AIT-la ahth"),
    ("í framtíðinni", "in the future", "phrase", "ee FRAHM-tee-thin-i"),
    ("á næstunni", "soon/shortly", "phrase", "ow NAIS-tun-i"),
    ("vonandi", "hopefully", "adverb", "VO-nahn-di"),
    ("kannski", "maybe/perhaps", "adverb", "KAHN-ski"),
    ("seinna", "later", "adverb", "SAYN-a"),
    ("einn daginn", "one day", "phrase", "aytn DAH-gin"),
    ("draumur", "dream", "noun", "DROI-mur"),
    ("markmið", "goal", "noun", "MARK-mith"),
    ("að vona", "to hope", "verb", "ahth VOH-na"),
    ("að áætla", "to plan/expect", "verb", "ahth OW-ayt-la"),
    ("líklega", "probably", "adverb", "LEEK-le-ga"),
    ("ólíklega", "unlikely", "adverb", "OH-leek-le-ga"),

    # Lesson 28: Review - practical situations
    ("staða", "situation", "noun", "STA-tha"),
    ("reynsla", "experience", "noun", "RAYN-sla"),
    ("aðstoð", "assistance", "noun", "AHTH-stohth"),
    ("upplýsingar", "information", "noun", "UP-lee-sing-ar"),
    ("ráð", "advice", "noun", "rowth"),
    ("að ráðleggja", "to advise", "verb", "ahth ROWTH-leg-ya"),
    ("virkilega", "really", "adverb", "VIR-ki-le-ga"),
    ("alveg", "completely", "adverb", "AHL-veg"),
    ("eiginlega", "actually", "adverb", "AY-gin-le-ga"),
    ("aftur", "again", "adverb", "AHF-tur"),
    ("aldrei", "never", "adverb", "AHLD-ray"),
    ("stundum", "sometimes", "adverb", "STUN-dum"),
    ("oft", "often", "adverb", "oft"),
    ("sjaldan", "rarely", "adverb", "SYAHL-dan"),
    ("yfirleitt", "usually", "adverb", "I-vir-layt"),

    # Lesson 29: Review - communication
    ("samskipti", "communication", "noun", "SAHM-skip-ti"),
    ("samtal", "conversation", "noun", "SAHM-tahl"),
    ("skilningur", "understanding", "noun", "SKIL-ning-ur"),
    ("að útskýra", "to explain", "verb", "ahth OOT-skee-ra"),
    ("að spyrja", "to ask", "verb", "ahth SPIR-ya"),
    ("að svara", "to answer", "verb", "ahth SVA-ra"),
    ("spurning", "question", "noun", "SPUR-ning"),
    ("svar", "answer", "noun", "svar"),
    ("rétt", "correct", "adjective", "ryeht"),
    ("misskilningur", "misunderstanding", "noun", "MIS-skil-ning-ur"),
    ("að þýða", "to translate", "verb", "ahth THEE-tha"),
    ("orð", "word", "noun", "orth"),
    ("setning", "sentence", "noun", "SET-ning"),
    ("mál", "language/matter", "noun", "mowl"),
    ("framburður", "pronunciation", "noun", "FRAHM-bur-thur"),

    # Lesson 30: Comprehensive review
    ("samantekt", "summary", "noun", "SA-mahn-tekt"),
    ("framfarir", "progress", "noun", "FRAHM-fa-rir"),
    ("þekking", "knowledge", "noun", "THEK-ing"),
    ("hæfni", "skill", "noun", "HAIV-ni"),
    ("sjálfstraust", "confidence", "noun", "SYOWLFS-troist"),
    ("æfing", "practice", "noun", "AI-ving"),
    ("að æfa", "to practice", "verb", "ahth AI-va"),
    ("endurtekning", "repetition", "noun", "EN-dur-TEK-ning"),
    ("framför", "improvement", "noun", "FRAHM-fuhr"),
    ("að halda áfram", "to continue", "verb", "ahth HAHL-da OW-fram"),
    ("næsta skref", "next step", "phrase", "NAIS-ta skrev"),
    ("markmið", "objective", "noun", "MARK-mith"),
    ("árangur", "result/success", "noun", "OW-rahn-gur"),
    ("til hamingju", "congratulations", "phrase", "til HA-ming-yu"),
    ("velkominn", "welcome", "adjective", "VEL-ko-min"),
]

# Icelandic core vocabulary for B1 (~750 words for 30 lessons, ~25 words/lesson)
# Advanced vocabulary for complex topics and abstract concepts
ICELANDIC_CORE_VOCABULARY_B1 = [
    # Lesson 1: Emotions and feelings
    ("tilfinning", "emotion/feeling", "noun", "TIL-fin-ning"),
    ("gleði", "joy/happiness", "noun", "GLAY-thi"),
    ("sorg", "sadness/grief", "noun", "sorg"),
    ("reiði", "anger", "noun", "RAY-thi"),
    ("ótti", "fear", "noun", "OHT-ti"),
    ("undrun", "surprise", "noun", "UND-run"),
    ("vonbrigði", "disappointment", "noun", "VON-brig-thi"),
    ("ánægja", "satisfaction", "noun", "OW-naig-ya"),
    ("þakklæti", "gratitude", "noun", "THAHK-lai-ti"),
    ("áhyggjur", "worry/anxiety", "noun", "OW-hig-yur"),
    ("efasemdir", "doubt", "noun", "E-va-sem-dir"),
    ("sjálfstraust", "self-confidence", "noun", "SYOWLFS-troist"),
    ("stoltur", "proud", "adjective", "STOL-tur"),
    ("svekkt", "let down", "adjective", "svekt"),
    ("stressaður", "stressed", "adjective", "STRES-a-thur"),
    ("rólega", "calmly", "adverb", "ROH-le-ga"),
    ("að finna fyrir", "to feel (emotion)", "verb", "ahth FIN-a FI-rir"),
    ("að hughreysta", "to comfort", "verb", "ahth HUG-hrayst-a"),
    ("sálrænn", "psychological", "adjective", "SOWL-raitn"),
    ("andlegur", "mental/spiritual", "adjective", "AHND-le-gur"),
    ("tilfinningalegur", "emotional", "adjective", "TIL-fin-ning-a-le-gur"),
    ("að tjá sig", "to express oneself", "verb", "ahth tyow sig"),
    ("innri", "inner", "adjective", "IN-ri"),
    ("að létta", "to relieve", "verb", "ahth LYEHT-a"),
    ("hugarástand", "state of mind", "noun", "HU-gar-OW-stahnd"),

    # Lesson 2: Relationships
    ("samband", "relationship", "noun", "SAHM-bahnd"),
    ("ástvin", "loved one", "noun", "OWST-vin"),
    ("trúlofun", "engagement", "noun", "TROO-lo-vun"),
    ("skilnaður", "divorce", "noun", "SKIL-na-thur"),
    ("sambýli", "cohabitation", "noun", "SAHM-bee-li"),
    ("hjónaband", "marriage", "noun", "HYOH-na-bahnd"),
    ("trúnaður", "trust/loyalty", "noun", "TROO-na-thur"),
    ("traust", "trust", "noun", "troist"),
    ("virðing", "respect", "noun", "VIR-thing"),
    ("skilningur", "understanding", "noun", "SKIL-ning-ur"),
    ("samskipti", "communication", "noun", "SAHM-skip-ti"),
    ("ágreiningur", "disagreement", "noun", "OW-gray-ning-ur"),
    ("sátt", "reconciliation", "noun", "sowt"),
    ("kærleikur", "affection", "noun", "KAIR-lay-kur"),
    ("einlægi", "sincerity", "noun", "AYN-lai-gi"),
    ("að efast um", "to doubt", "verb", "ahth E-vast um"),
    ("að styðja", "to support", "verb", "ahth STITH-ya"),
    ("að vernda", "to protect", "verb", "ahth VERN-da"),
    ("að sættast", "to reconcile", "verb", "ahth SAIT-ast"),
    ("náinn", "close (intimate)", "adjective", "NOW-in"),
    ("fjarlægur", "distant", "adjective", "FYAR-lai-gur"),
    ("hólpur", "supportive", "adjective", "HOHL-pur"),
    ("kæra", "dear/beloved", "adjective", "KAI-ra"),
    ("einmana", "lonely", "adjective", "AYN-ma-na"),
    ("sameiginlegur", "mutual/shared", "adjective", "SA-mayg-in-le-gur"),

    # Lesson 3: Personality traits
    ("persónuleiki", "personality", "noun", "per-SOH-nu-lay-ki"),
    ("eðli", "nature/character", "noun", "ETH-li"),
    ("einkenni", "characteristic", "noun", "AYN-ken-ni"),
    ("kostir", "strengths/qualities", "noun", "KOS-tir"),
    ("gallar", "flaws/weaknesses", "noun", "GAHL-ar"),
    ("heiðarlegur", "honest", "adjective", "HAY-thar-le-gur"),
    ("óheiðarlegur", "dishonest", "adjective", "OH-hay-thar-le-gur"),
    ("örlátaður", "generous", "adjective", "UHR-low-ta-thur"),
    ("nískur", "stingy", "adjective", "NEES-kur"),
    ("þolinmóður", "patient", "adjective", "THO-lin-MOH-thur"),
    ("óþolinmóður", "impatient", "adjective", "OH-tho-lin-MOH-thur"),
    ("samviskusamur", "conscientious", "adjective", "SAHM-vis-ku-SA-mur"),
    ("ábyrgur", "responsible", "adjective", "OW-bir-gur"),
    ("óábyrgur", "irresponsible", "adjective", "OH-ow-bir-gur"),
    ("metnaðargjarn", "ambitious", "adjective", "MET-na-thar-GYARDN"),
    ("latur", "lazy", "adjective", "LA-tur"),
    ("duglegur", "hardworking", "adjective", "DUG-le-gur"),
    ("skapgóður", "good-tempered", "adjective", "SKAHP-GOH-thur"),
    ("skapillur", "bad-tempered", "adjective", "SKAHP-IL-ur"),
    ("félagslyndur", "sociable", "adjective", "FYE-lahgs-lin-dur"),
    ("innhverfur", "introverted", "adjective", "IN-kver-fur"),
    ("úthverfur", "extroverted", "adjective", "OOT-kver-fur"),
    ("hugulsam", "thoughtful", "adjective", "HUG-ul-sahm"),
    ("forvitin", "curious", "adjective", "FOR-vi-tin"),
    ("skapgerð", "temperament", "noun", "SKAHP-gerth"),

    # Lesson 4: Values and beliefs
    ("gildi", "value", "noun", "GIL-di"),
    ("trú", "belief/faith", "noun", "troo"),
    ("siðferði", "ethics/morals", "noun", "SITH-fer-thi"),
    ("réttlæti", "justice", "noun", "RYEHT-lai-ti"),
    ("jafnrétti", "equality", "noun", "YAHV-n-ryeht-i"),
    ("frelsi", "freedom", "noun", "FREL-si"),
    ("friður", "peace", "noun", "FRITH-ur"),
    ("sannleikur", "truth", "noun", "SAHN-lay-kur"),
    ("heiður", "honor", "noun", "HAY-thur"),
    ("trúverðugleiki", "credibility", "noun", "TROO-ver-thug-lay-ki"),
    ("sannfæring", "conviction", "noun", "SAHN-fair-ing"),
    ("átrúnaður", "religious faith", "noun", "OW-troo-na-thur"),
    ("heimspeki", "philosophy", "noun", "HAYMS-pe-ki"),
    ("siðvenja", "custom", "noun", "SITH-ven-ya"),
    ("regla", "rule/principle", "noun", "REG-la"),
    ("að trúa á", "to believe in", "verb", "ahth TROO-a ow"),
    ("að virða", "to respect/honor", "verb", "ahth VIR-tha"),
    ("að styðja", "to support", "verb", "ahth STITH-ya"),
    ("að berjast fyrir", "to fight for", "verb", "ahth BER-yast FI-rir"),
    ("heilagur", "sacred", "adjective", "HAY-la-gur"),
    ("veraldlegur", "secular", "adjective", "VE-rald-le-gur"),
    ("siðferðilegur", "moral", "adjective", "SITH-fer-thi-le-gur"),
    ("trúaður", "religious", "adjective", "TROO-a-thur"),
    ("verðugur", "worthy", "adjective", "VER-thu-gur"),
    ("dygð", "virtue", "noun", "dygth"),

    # Lesson 5: Dreams and goals
    ("draumur", "dream", "noun", "DROI-mur"),
    ("markmið", "goal/objective", "noun", "MARK-mith"),
    ("framtíðarsýn", "vision for future", "noun", "FRAHM-tee-thar-seen"),
    ("metnað", "ambition", "noun", "MET-nath"),
    ("stefna", "direction/aim", "noun", "STEV-na"),
    ("árangur", "success/result", "noun", "OW-rahn-gur"),
    ("misheppni", "failure", "noun", "MIS-hep-ni"),
    ("áskorun", "challenge", "noun", "OWS-ko-run"),
    ("hindrun", "obstacle", "noun", "HIN-drun"),
    ("tækifæri", "opportunity", "noun", "TAI-ki-fair-i"),
    ("úrræði", "resource/solution", "noun", "OOR-rai-thi"),
    ("áætlun", "plan", "noun", "OW-ayt-lun"),
    ("skref", "step", "noun", "skrev"),
    ("framför", "progress", "noun", "FRAHM-fuhr"),
    ("að ná", "to achieve", "verb", "ahth now"),
    ("að stefna að", "to aim for", "verb", "ahth STEV-na ahth"),
    ("að einbeita sér", "to focus", "verb", "ahth AYN-bay-ta syer"),
    ("að yfirvinna", "to overcome", "verb", "ahth I-vir-VIN-a"),
    ("að þróast", "to develop", "verb", "ahth THROH-ast"),
    ("að breyta", "to change", "verb", "ahth BRAY-ta"),
    ("raunhæfur", "realistic", "adjective", "ROIN-hai-fur"),
    ("óraunhæfur", "unrealistic", "adjective", "OH-roin-hai-fur"),
    ("skammtíma", "short-term", "adjective", "SKAHM-tee-ma"),
    ("langtíma", "long-term", "adjective", "LAHNG-tee-ma"),
    ("framtíðar", "future (adj)", "adjective", "FRAHM-tee-thar"),

    # Lesson 6: News and media
    ("fréttir", "news", "noun", "FRYEHT-ir"),
    ("fjölmiðlar", "media", "noun", "FYUHL-mith-lar"),
    ("fréttamaður", "journalist", "noun", "FRYEHT-a-MA-thur"),
    ("ritstjóri", "editor", "noun", "RIT-styoh-ri"),
    ("þáttur", "program/episode", "noun", "THOWT-ur"),
    ("viðtal", "interview", "noun", "VITH-tahl"),
    ("greinargerð", "report", "noun", "GRAY-nar-gerth"),
    ("fyrirsögn", "headline", "noun", "FI-rir-SUHGN"),
    ("heimild", "source", "noun", "HAYM-ild"),
    ("staðreynd", "fact", "noun", "STATH-raynd"),
    ("skoðun", "opinion", "noun", "SKOH-thun"),
    ("útsendir", "broadcast", "adjective", "OOT-sen-dir"),
    ("beint", "live (broadcast)", "adverb", "baynt"),
    ("óhlutdrægur", "unbiased", "adjective", "OH-hlut-drai-gur"),
    ("hlutdrægur", "biased", "adjective", "HLUT-drai-gur"),
    ("að greina frá", "to report", "verb", "ahth GRAY-na frow"),
    ("að rannsaka", "to investigate", "verb", "ahth RAHN-sa-ka"),
    ("að birta", "to publish", "verb", "ahth BIR-ta"),
    ("að fylgjast með", "to follow/watch", "verb", "ahth FIL-gyast meth"),
    ("falsfréttir", "fake news", "noun", "FAHLS-fryeht-ir"),
    ("samfélagsmiðlar", "social media", "noun", "SAHM-fyeh-lahgs-MITH-lar"),
    ("straumspilaður", "streamed", "adjective", "STROIM-spi-la-thur"),
    ("áskrifandi", "subscriber", "noun", "OW-skri-vahn-di"),
    ("áhorfendur", "viewers/audience", "noun", "OW-hor-ven-dur"),
    ("lesendur", "readers", "noun", "LE-sen-dur"),

    # Lesson 7: Environment
    ("umhverfi", "environment", "noun", "UM-kver-vi"),
    ("náttúra", "nature", "noun", "NOW-too-ra"),
    ("loftslagsbreytingar", "climate change", "noun", "LOFT-slahgs-BRAY-ting-ar"),
    ("hlýnun jarðar", "global warming", "noun", "HLEE-nun YAR-thar"),
    ("gróðurhúsaáhrif", "greenhouse effect", "noun", "GROH-thur-HOO-sa-OW-hriv"),
    ("mengun", "pollution", "noun", "MENG-un"),
    ("úrgangur", "waste", "noun", "OOR-gahng-ur"),
    ("endurvinnsla", "recycling", "noun", "EN-dur-VIN-sla"),
    ("sjálfbærni", "sustainability", "noun", "SYOWLF-bair-ni"),
    ("orkugjafi", "energy source", "noun", "OR-ku-GYA-vi"),
    ("endurnýjanlegur", "renewable", "adjective", "EN-dur-NEEYA-an-le-gur"),
    ("kolefnisspor", "carbon footprint", "noun", "KO-lev-nis-spor"),
    ("vistkerfið", "ecosystem", "noun", "VIST-ker-vith"),
    ("líffjölbreytileiki", "biodiversity", "noun", "LEEF-fyuhl-BRAY-ti-lay-ki"),
    ("dýravernd", "animal protection", "noun", "DEE-ra-vernd"),
    ("útrýming", "extinction", "noun", "OOT-ree-ming"),
    ("að vernda", "to protect", "verb", "ahth VERN-da"),
    ("að menga", "to pollute", "verb", "ahth MENG-a"),
    ("að endurvinna", "to recycle", "verb", "ahth EN-dur-VIN-a"),
    ("að minnka", "to reduce", "verb", "ahth MIN-ka"),
    ("umhverfisvænn", "environmentally friendly", "adjective", "UM-kver-vis-vaitn"),
    ("gróður", "vegetation", "noun", "GROH-thur"),
    ("vatnsbóla", "water reservoir", "noun", "VAHTS-boh-la"),
    ("skógarhögg", "deforestation", "noun", "SKOH-gar-huhg"),
    ("náttúruauðlindir", "natural resources", "noun", "NOW-too-ru-OITH-lin-dir"),

    # Lesson 8: Technology
    ("tækni", "technology", "noun", "TAIK-ni"),
    ("tölva", "computer", "noun", "TUHL-va"),
    ("hugbúnaður", "software", "noun", "HUG-boo-na-thur"),
    ("vélbúnaður", "hardware", "noun", "VYEL-boo-na-thur"),
    ("forrit", "application/program", "noun", "FOR-it"),
    ("gagnagrunnur", "database", "noun", "GAHG-na-GRUN-ur"),
    ("netöryggi", "cybersecurity", "noun", "NET-uhr-ig-i"),
    ("dulkóðun", "encryption", "noun", "DUL-koh-thun"),
    ("gervigreind", "artificial intelligence", "noun", "GER-vi-graynd"),
    ("sjálfvirkni", "automation", "noun", "SYOWLF-virk-ni"),
    ("þráðlaust", "wireless", "adjective", "THROWTH-loist"),
    ("snjalltæki", "smart device", "noun", "SNYAHTL-tai-ki"),
    ("skýjaþjónusta", "cloud service", "noun", "SKYY-a-THYOH-nus-ta"),
    ("netþjónn", "server", "noun", "NET-thyohdn"),
    ("viðmót", "interface", "noun", "VITH-moht"),
    ("að uppfæra", "to update", "verb", "ahth UP-fair-a"),
    ("að hlaða niður", "to download", "verb", "ahth HLAH-tha NI-thur"),
    ("að hlaða upp", "to upload", "verb", "ahth HLAH-tha up"),
    ("að tengja", "to connect", "verb", "ahth TENG-ya"),
    ("að aftengjast", "to disconnect", "verb", "ahth AHV-teng-yast"),
    ("stafrænn", "digital", "adjective", "STAHF-raitn"),
    ("tækniþróun", "technological development", "noun", "TAIK-ni-THROH-un"),
    ("nýsköpun", "innovation", "noun", "NEE-skuh-pun"),
    ("kerfið", "system", "noun", "KER-vith"),
    ("örgjörvi", "processor", "noun", "UHR-gyuhr-vi"),

    # Lesson 9: Education
    ("menntun", "education", "noun", "MENT-un"),
    ("skólakerfi", "school system", "noun", "SKOH-la-KER-vi"),
    ("grunnskóli", "primary school", "noun", "GRUN-skoh-li"),
    ("framhaldsskóli", "secondary school", "noun", "FRAHM-halds-SKOH-li"),
    ("háskóli", "university", "noun", "HOW-skoh-li"),
    ("námsbraut", "study program", "noun", "NOWMS-broit"),
    ("próf", "exam", "noun", "prohv"),
    ("verkefni", "assignment/project", "noun", "VER-kev-ni"),
    ("einkunn", "grade", "noun", "AYN-kun"),
    ("viðfangsefni", "subject matter", "noun", "VITH-fahng-SEV-ni"),
    ("rannsókn", "research", "noun", "RAHN-sohkn"),
    ("fræðimaður", "scholar", "noun", "FRAI-thi-MA-thur"),
    ("kennsla", "teaching", "noun", "KEN-sla"),
    ("nám", "studies", "noun", "nowm"),
    ("námsstyrkur", "scholarship", "noun", "NOWMS-stir-kur"),
    ("að útskrifast", "to graduate", "verb", "ahth OOT-skri-vast"),
    ("að sækja", "to attend", "verb", "ahth SAI-kya"),
    ("að læra utan", "to memorize", "verb", "ahth LAI-ra OO-tahn"),
    ("að greina", "to analyze", "verb", "ahth GRAY-na"),
    ("að íhuga", "to consider", "verb", "ahth EE-hu-ga"),
    ("fræðilegur", "academic/theoretical", "adjective", "FRAI-thi-le-gur"),
    ("hagnýtur", "practical", "adjective", "HAHG-nee-tur"),
    ("krefjandi", "demanding", "adjective", "KREV-yahn-di"),
    ("námsgögn", "study materials", "noun", "NOWMS-guhgn"),
    ("lokaritgerð", "thesis", "noun", "LO-ka-RIT-gerth"),

    # Lesson 10: Health and fitness
    ("heilsa", "health", "noun", "HAYL-sa"),
    ("líkamsrækt", "fitness", "noun", "LEE-kahms-raikt"),
    ("þrek", "stamina/endurance", "noun", "threk"),
    ("þol", "endurance", "noun", "thol"),
    ("sveigjanleiki", "flexibility", "noun", "SVAYG-yan-lay-ki"),
    ("fita", "fat", "noun", "FI-ta"),
    ("prótein", "protein", "noun", "proh-TAYN"),
    ("næring", "nutrition", "noun", "NAI-ring"),
    ("mataræði", "diet", "noun", "MA-ta-rai-thi"),
    ("þyngd", "weight", "noun", "thingth"),
    ("líkamsþyngdarstuðull", "BMI", "noun", "LEE-kahms-THINGTH-ar-STUTH-ul"),
    ("æfing", "exercise/workout", "noun", "AI-ving"),
    ("þjálfari", "trainer/coach", "noun", "THYOWL-va-ri"),
    ("líkamsbygging", "bodybuilding", "noun", "LEE-kahms-BIG-ing"),
    ("andleg heilsa", "mental health", "noun", "AHND-leg HAYL-sa"),
    ("að æfa", "to exercise", "verb", "ahth AI-va"),
    ("að hreyfa sig", "to move/exercise", "verb", "ahth HRAY-va sig"),
    ("að grenna sig", "to lose weight", "verb", "ahth GREN-a sig"),
    ("að styrkja", "to strengthen", "verb", "ahth STIR-kya"),
    ("að slaka á", "to relax", "verb", "ahth SLAH-ka ow"),
    ("heilbrigður", "healthy", "adjective", "HAYL-brig-thur"),
    ("óheilbrigður", "unhealthy", "adjective", "OH-hayl-brig-thur"),
    ("þjálfaður", "trained/fit", "adjective", "THYOWL-va-thur"),
    ("streita", "stress", "noun", "STRAY-ta"),
    ("svefnvenjur", "sleep habits", "noun", "SVEV-n-VEN-yur"),

    # Lesson 11: Job interviews
    ("atvinnuviðtal", "job interview", "noun", "AHT-vin-u-VITH-tahl"),
    ("umsækjandi", "applicant", "noun", "UM-sai-kyahn-di"),
    ("starfsreynsla", "work experience", "noun", "STARFS-rayn-sla"),
    ("menntun", "education", "noun", "MENT-un"),
    ("hæfni", "qualification/skill", "noun", "HAIV-ni"),
    ("styrkleikar", "strengths", "noun", "STIR-klay-kar"),
    ("veikleikar", "weaknesses", "noun", "VAYK-lay-kar"),
    ("kröfur", "requirements", "noun", "KRUH-vur"),
    ("laun", "salary/wage", "noun", "loin"),
    ("hlunnindi", "benefits", "noun", "HLUN-in-di"),
    ("vinnusamningur", "employment contract", "noun", "VIN-u-SAHM-ning-ur"),
    ("reynslutími", "probation period", "noun", "RAYN-slu-TEE-mi"),
    ("starfslýsing", "job description", "noun", "STARFS-LEE-sing"),
    ("ráðning", "hiring", "noun", "ROWTH-ning"),
    ("fækka umsóknum", "shortlisting", "noun", "FAIK-a UM-sohk-num"),
    ("að sækja um starf", "to apply for a job", "verb", "ahth SAI-kya um stahrf"),
    ("að kynna sig", "to introduce oneself", "verb", "ahth KIN-a sig"),
    ("að nefna", "to mention", "verb", "ahth NEV-na"),
    ("að sýna fram á", "to demonstrate", "verb", "ahth SEE-na frahm ow"),
    ("að þróa", "to develop", "verb", "ahth THROH-a"),
    ("hæfur", "qualified", "adjective", "HAI-vur"),
    ("reynslumikill", "experienced", "adjective", "RAYN-slu-MI-kitl"),
    ("áhugasamur", "enthusiastic", "adjective", "OW-hu-ga-SA-mur"),
    ("sveigjanlegur", "flexible", "adjective", "SVAYG-yan-le-gur"),
    ("sjálfstæður", "independent", "adjective", "SYOWLF-stai-thur"),

    # Lesson 12: Business vocabulary
    ("fyrirtæki", "company/business", "noun", "FI-rir-TAI-ki"),
    ("viðskipti", "business/trade", "noun", "VITH-skip-ti"),
    ("markaðssetning", "marketing", "noun", "MAR-kaths-SET-ning"),
    ("sala", "sales", "noun", "SA-la"),
    ("hagnaður", "profit", "noun", "HAHG-na-thur"),
    ("tap", "loss", "noun", "tahp"),
    ("velta", "turnover", "noun", "VEL-ta"),
    ("fjárfesting", "investment", "noun", "FYOWR-fes-ting"),
    ("samkeppni", "competition", "noun", "SAHM-kep-ni"),
    ("markaður", "market", "noun", "MAR-ka-thur"),
    ("viðskiptavinur", "customer", "noun", "VITH-skip-ta-VI-nur"),
    ("birgði", "supplier", "noun", "BIR-gi"),
    ("samningur", "contract", "noun", "SAHM-ning-ur"),
    ("stefna", "strategy/policy", "noun", "STEV-na"),
    ("fjármál", "finance", "noun", "FYOWR-mowl"),
    ("að fjárfesta", "to invest", "verb", "ahth FYOWR-fes-ta"),
    ("að samþykkja", "to approve", "verb", "ahth SAHM-thik-ya"),
    ("að semja", "to negotiate", "verb", "ahth SEM-ya"),
    ("að eiga viðskipti", "to do business", "verb", "ahth AY-ga VITH-skip-ti"),
    ("að stækka", "to expand", "verb", "ahth STAIK-a"),
    ("arðbær", "profitable", "adjective", "ARTH-bair"),
    ("samkeppnishæfur", "competitive", "adjective", "SAHM-kep-nis-HAI-vur"),
    ("fyrirtækjamenning", "corporate culture", "noun", "FI-rir-TAI-kya-MEN-ing"),
    ("viðskiptaáætlun", "business plan", "noun", "VITH-skip-ta-OW-ayt-lun"),
    ("aðalstöðvar", "headquarters", "noun", "A-thal-STUHTH-var"),

    # Lesson 13: Presentations
    ("kynning", "presentation", "noun", "KIN-ing"),
    ("ræða", "speech", "noun", "RAI-tha"),
    ("glæra", "slide", "noun", "GLAI-ra"),
    ("áhorfendur", "audience", "noun", "OW-hor-ven-dur"),
    ("efni", "content", "noun", "EV-ni"),
    ("aðalatriði", "main point", "noun", "A-thahl-AHT-ri-thi"),
    ("uppbygging", "structure", "noun", "UP-big-ing"),
    ("inngangur", "introduction", "noun", "IN-gahng-ur"),
    ("meginmál", "main body", "noun", "ME-gin-mowl"),
    ("niðurstaða", "conclusion", "noun", "NI-thur-STA-tha"),
    ("töluliður", "bullet point", "noun", "TUH-lu-LI-thur"),
    ("línurit", "line graph", "noun", "LEE-nu-rit"),
    ("súlurit", "bar chart", "noun", "SOO-lu-rit"),
    ("kökurit", "pie chart", "noun", "KUH-ku-rit"),
    ("mynd", "image/figure", "noun", "mind"),
    ("að kynna", "to present", "verb", "ahth KIN-a"),
    ("að skýra", "to clarify", "verb", "ahth SKEE-ra"),
    ("að draga saman", "to summarize", "verb", "ahth DRA-ga SA-mahn"),
    ("að undirstrika", "to emphasize", "verb", "ahth UN-dir-STRI-ka"),
    ("að svara spurningum", "to answer questions", "verb", "ahth SVA-ra SPUR-ning-um"),
    ("skýr", "clear", "adjective", "skeer"),
    ("skipulagður", "organized", "adjective", "SKI-pu-lahg-thur"),
    ("sannfærandi", "convincing", "adjective", "SAHN-fair-ahn-di"),
    ("upplýsandi", "informative", "adjective", "UP-lee-sahn-di"),
    ("stutta samantekt", "brief summary", "noun", "STUT-a SA-mahn-tekt"),

    # Lesson 14: Negotiations
    ("samningaviðræður", "negotiations", "noun", "SAHM-ning-a-VITH-rai-thur"),
    ("tilboð", "offer", "noun", "TIL-both"),
    ("gagntilboð", "counter-offer", "noun", "GAHGN-til-both"),
    ("skilyrði", "condition/term", "noun", "SKI-lir-thi"),
    ("málamiðlun", "compromise", "noun", "MOW-la-MITH-lun"),
    ("ágreiningur", "dispute", "noun", "OW-GRAY-ning-ur"),
    ("lausn", "solution", "noun", "loisn"),
    ("samkomulag", "agreement", "noun", "SAHM-ko-mu-lahg"),
    ("aðili", "party (in negotiation)", "noun", "A-thi-li"),
    ("hagsmunir", "interests", "noun", "HAHGS-mu-nir"),
    ("þrýstingur", "pressure", "noun", "THREES-ting-ur"),
    ("svigrúm", "flexibility/room", "noun", "SVIG-room"),
    ("rökstyðja", "to justify", "verb", "RUHK-stith-ya"),
    ("að semja um", "to negotiate", "verb", "ahth SEM-ya um"),
    ("að bjóða", "to offer", "verb", "ahth BYOH-tha"),
    ("að samþykkja", "to accept", "verb", "ahth SAHM-thik-ya"),
    ("að hafna", "to reject", "verb", "ahth HAHV-na"),
    ("að ganga frá", "to finalize", "verb", "ahth GAHNG-a frow"),
    ("að þrýsta á", "to push for", "verb", "ahth THREES-ta ow"),
    ("sanngjarn", "fair", "adjective", "SAHN-gyardn"),
    ("ósanngjarn", "unfair", "adjective", "OH-sahn-gyardn"),
    ("samningahæfni", "negotiation skills", "noun", "SAHM-ning-a-HAIV-ni"),
    ("að endurskoða", "to review/revise", "verb", "ahth EN-dur-SKOH-tha"),
    ("undirritun", "signature", "noun", "UN-dir-RI-tun"),
    ("lokasamningur", "final agreement", "noun", "LO-ka-SAHM-ning-ur"),

    # Lesson 15: Workplace culture
    ("vinnustaðamenning", "workplace culture", "noun", "VIN-u-STA-tha-MEN-ing"),
    ("starfsandi", "work morale", "noun", "STARFS-ahn-di"),
    ("teymisandinn", "team spirit", "noun", "TAY-mis-AHN-din"),
    ("samstarf", "collaboration", "noun", "SAHM-stahrf"),
    ("leiðtogi", "leader", "noun", "LAYTH-toh-gi"),
    ("hvatning", "motivation", "noun", "KVAHT-ning"),
    ("endurgjöf", "feedback", "noun", "EN-dur-gyuhv"),
    ("faglegt", "professional", "adjective", "FAHG-legt"),
    ("siðareglur", "code of conduct", "noun", "SI-tha-REG-lur"),
    ("jafnvægi", "balance", "noun", "YAHV-n-vai-gi"),
    ("streita á vinnustað", "workplace stress", "noun", "STRAY-ta ow VIN-u-stahth"),
    ("sífellt nám", "continuous learning", "noun", "SEE-fellt nowm"),
    ("stöðuhækkun", "promotion", "noun", "STUH-thu-HAIK-un"),
    ("umbun", "reward", "noun", "UM-bun"),
    ("viðurkenning", "recognition", "noun", "VI-thur-KEN-ing"),
    ("að hvetja", "to motivate", "verb", "ahth KVET-ya"),
    ("að styðja", "to support", "verb", "ahth STITH-ya"),
    ("að þróast", "to develop", "verb", "ahth THROH-ast"),
    ("að leiða", "to lead", "verb", "ahth LAY-tha"),
    ("að vinna saman", "to work together", "verb", "ahth VIN-a SA-mahn"),
    ("skilvirk", "efficient", "adjective", "SKIL-virk"),
    ("skapandi", "creative", "adjective", "SKA-pahn-di"),
    ("frumkvöðull", "entrepreneur/pioneer", "noun", "FRUM-kvuh-thul"),
    ("fjarvinna", "remote work", "noun", "FYAR-vin-a"),
    ("sveigjanlegar vinnustundir", "flexible hours", "noun", "SVAYG-yan-leg-ar VIN-u-STUN-dir"),

    # Lesson 16: Problem solving
    ("vandamál", "problem", "noun", "VAN-da-mowl"),
    ("vandamálalausn", "problem solving", "noun", "VAN-da-mowl-a-loisn"),
    ("greining", "analysis", "noun", "GRAY-ning"),
    ("rót vandamáls", "root cause", "noun", "roht VAN-da-mowls"),
    ("valkostir", "options", "noun", "VAHL-kos-tir"),
    ("áhættumat", "risk assessment", "noun", "OW-hait-u-maht"),
    ("afleiðingar", "consequences", "noun", "AHV-LAYTH-ing-ar"),
    ("lausnir", "solutions", "noun", "LOIS-nir"),
    ("aðferð", "method", "noun", "ATH-ferth"),
    ("skref", "step", "noun", "skrev"),
    ("framkvæmd", "implementation", "noun", "FRAHM-kvaimd"),
    ("mat", "evaluation", "noun", "maht"),
    ("úrbætur", "improvements", "noun", "OOR-bai-tur"),
    ("hugmyndaflug", "brainstorming", "noun", "HUG-min-da-flug"),
    ("forgangsröðun", "prioritization", "noun", "FOR-gahngs-RUH-thun"),
    ("að greina", "to analyze", "verb", "ahth GRAY-na"),
    ("að meta", "to evaluate", "verb", "ahth ME-ta"),
    ("að velja", "to choose", "verb", "ahth VEL-ya"),
    ("að útfæra", "to implement", "verb", "ahth OOT-fair-a"),
    ("að leysa", "to solve", "verb", "ahth LAY-sa"),
    ("kerfisbundinn", "systematic", "adjective", "KER-vis-bun-din"),
    ("skapandi", "creative", "adjective", "SKA-pahn-di"),
    ("rökréttur", "logical", "adjective", "RUHK-ryeht-ur"),
    ("hugsun", "thinking", "noun", "HUG-sun"),
    ("gagnrýnin hugsun", "critical thinking", "noun", "GAHGN-ree-nin HUG-sun"),

    # Lesson 17: Giving advice
    ("ráð", "advice", "noun", "rowth"),
    ("ráðlegging", "recommendation", "noun", "ROWTH-leg-ing"),
    ("tillaga", "suggestion", "noun", "TIL-a-ga"),
    ("leiðbeining", "guidance", "noun", "LAYTH-bay-ning"),
    ("fyrirvari", "warning", "noun", "FI-rir-VA-ri"),
    ("áminning", "reminder", "noun", "OW-min-ning"),
    ("reynsla", "experience", "noun", "RAYN-sla"),
    ("ráðgjafi", "advisor", "noun", "ROWTH-GYA-vi"),
    ("leiðsögn", "mentoring", "noun", "LAYTH-suhgn"),
    ("sérfræðingur", "expert", "noun", "SYER-frai-thing-ur"),
    ("að ráðleggja", "to advise", "verb", "ahth ROWTH-leg-ya"),
    ("að mæla með", "to recommend", "verb", "ahth MAI-la meth"),
    ("að vara við", "to warn against", "verb", "ahth VA-ra vith"),
    ("að benda á", "to point out", "verb", "ahth BEN-da ow"),
    ("að leggja til", "to suggest", "verb", "ahth LEG-ya til"),
    ("þú ættir að", "you should", "phrase", "thoo AIT-tir ahth"),
    ("ef ég væri þú", "if I were you", "phrase", "ev yeh VAI-ri thoo"),
    ("mér finnst best", "I think it's best", "phrase", "myer finst best"),
    ("passaðu þig á", "watch out for", "phrase", "PAHS-a-thu thig ow"),
    ("reyndu að", "try to", "phrase", "RAYN-du ahth"),
    ("gagnlegur", "useful", "adjective", "GAHGN-le-gur"),
    ("óþarfur", "unnecessary", "adjective", "OH-thar-vur"),
    ("hættulegur", "dangerous", "adjective", "HAIT-u-le-gur"),
    ("ráðlögð aðgerð", "recommended action", "noun", "ROWTH-luhgth ATH-gerth"),
    ("varkárni", "caution", "noun", "VAR-kowr-ni"),

    # Lesson 18: Hypothetical situations
    ("tilgáta", "hypothesis", "noun", "TIL-gow-ta"),
    ("ef", "if", "conjunction", "ev"),
    ("ef svo væri", "if that were the case", "phrase", "ev svoh VAI-ri"),
    ("ímyndaður", "imaginary", "adjective", "EE-min-da-thur"),
    ("hugsanlegur", "possible", "adjective", "HUG-sahn-le-gur"),
    ("ólíklegur", "unlikely", "adjective", "OH-leek-le-gur"),
    ("líklegur", "likely", "adjective", "LEEK-le-gur"),
    ("raunverulegur", "real/actual", "adjective", "ROIN-ve-ru-le-gur"),
    ("skilyrði", "condition", "noun", "SKI-lir-thi"),
    ("forsenda", "premise", "noun", "FOR-sen-da"),
    ("af því", "because", "conjunction", "ahv thee"),
    ("þá", "then", "adverb", "thow"),
    ("annars", "otherwise", "adverb", "AHN-ars"),
    ("hvað ef", "what if", "phrase", "kvath ev"),
    ("gefum okkur", "let's assume", "phrase", "GYE-vum OK-ur"),
    ("að ímynda sér", "to imagine", "verb", "ahth EE-min-da syer"),
    ("að gera ráð fyrir", "to assume", "verb", "ahth GYE-ra rowth FI-rir"),
    ("að spá", "to predict", "verb", "ahth spow"),
    ("að velta fyrir sér", "to wonder", "verb", "ahth VEL-ta FI-rir syer"),
    ("myndi", "would", "verb_form", "MIN-di"),
    ("gæti", "could", "verb_form", "GAI-ti"),
    ("ætti", "should/ought", "verb_form", "AIT-ti"),
    ("vildi", "would want", "verb_form", "VIL-di"),
    ("draumsýn", "vision/scenario", "noun", "DROIM-seen"),
    ("möguleiki", "possibility", "noun", "MUH-gu-lay-ki"),

    # Lesson 19: Explaining processes
    ("ferli", "process", "noun", "FER-li"),
    ("þrep", "stage/step", "noun", "threp"),
    ("skref", "step", "noun", "skrev"),
    ("röð", "sequence", "noun", "ruhth"),
    ("aðgerð", "action/operation", "noun", "ATH-gerth"),
    ("fyrst", "first", "adverb", "first"),
    ("síðan", "then", "adverb", "SEE-than"),
    ("næst", "next", "adverb", "naist"),
    ("að lokum", "finally", "adverb", "ahth LO-kum"),
    ("á meðan", "while/during", "conjunction", "ow ME-than"),
    ("eftir það", "after that", "phrase", "EV-tir thahth"),
    ("fyrir það", "before that", "phrase", "FI-rir thahth"),
    ("samhliða", "simultaneously", "adverb", "SAHM-hli-tha"),
    ("flæðirit", "flowchart", "noun", "FLAI-thi-rit"),
    ("leiðbeiningar", "instructions", "noun", "LAYTH-bay-ning-ar"),
    ("að útskýra", "to explain", "verb", "ahth OOT-skee-ra"),
    ("að lýsa", "to describe", "verb", "ahth LEE-sa"),
    ("að sýna", "to show", "verb", "ahth SEE-na"),
    ("að fylgja", "to follow", "verb", "ahth FIL-gya"),
    ("að ljúka", "to complete", "verb", "ahth LYOO-ka"),
    ("nákvæmur", "precise", "adjective", "NOW-kvaim-ur"),
    ("skýringarmynd", "diagram", "noun", "SKEE-ring-ar-mind"),
    ("að koma í kjölfarið", "to follow up", "verb", "ahth KO-ma ee KYUHL-var-ith"),
    ("inntak", "input", "noun", "IN-tahk"),
    ("úttak", "output", "noun", "OOT-tahk"),

    # Lesson 20: Cause and effect
    ("orsök", "cause", "noun", "OR-suhk"),
    ("afleiðing", "effect/consequence", "noun", "AHV-layth-ing"),
    ("áhrif", "impact", "noun", "OW-hriv"),
    ("orsök og afleiðing", "cause and effect", "phrase", "OR-suhk og AHV-layth-ing"),
    ("tengsl", "connection", "noun", "TENG-sl"),
    ("vegna", "because of", "preposition", "VEG-na"),
    ("þar af leiðandi", "consequently", "adverb", "thar ahv LAY-thahn-di"),
    ("þess vegna", "therefore", "adverb", "thess VEG-na"),
    ("sem leiðir til", "which leads to", "phrase", "sem LAY-thir til"),
    ("hafa áhrif á", "to affect", "phrase", "HA-va OW-hriv ow"),
    ("af völdum", "caused by", "phrase", "ahv VUHL-dum"),
    ("undirliggjandi", "underlying", "adjective", "UN-dir-LIG-yahn-di"),
    ("aðalástæða", "main reason", "noun", "A-thahl-OW-stai-tha"),
    ("keðjuverkun", "chain reaction", "noun", "KETH-yu-VER-kun"),
    ("niðurstaða", "result", "noun", "NI-thur-STA-tha"),
    ("að valda", "to cause", "verb", "ahth VAHL-da"),
    ("að leiða til", "to lead to", "verb", "ahth LAY-tha til"),
    ("að hafa áhrif", "to have effect", "verb", "ahth HA-va OW-hriv"),
    ("að koma af", "to result from", "verb", "ahth KO-ma ahv"),
    ("að stuðla að", "to contribute to", "verb", "ahth STUTH-la ahth"),
    ("afleiddar afleiðingar", "secondary effects", "noun", "AHV-layd-ar AHV-layth-ing-ar"),
    ("fyrirsjáanlegur", "predictable", "adjective", "FI-rir-SYOW-ahn-le-gur"),
    ("ófyrirséður", "unforeseen", "adjective", "OH-fi-rir-SYEH-thur"),
    ("skýring", "explanation", "noun", "SKEE-ring"),
    ("orsakasamband", "causal relationship", "noun", "OR-sa-ka-SAHM-bahnd"),

    # Lesson 21: Traditions and customs
    ("hefð", "tradition", "noun", "hevth"),
    ("siður", "custom", "noun", "SI-thur"),
    ("menning", "culture", "noun", "MEN-ing"),
    ("arfleifð", "heritage", "noun", "ARV-layv-th"),
    ("þjóðerni", "nationality", "noun", "THYOHTH-er-ni"),
    ("hátíðahöld", "celebrations", "noun", "HOW-teeth-a-HUHLD"),
    ("matarmenning", "food culture", "noun", "MA-tar-MEN-ing"),
    ("þjóðbúningur", "national costume", "noun", "THYOHTH-BOO-ning-ur"),
    ("þjóðdans", "folk dance", "noun", "THYOHTH-dahns"),
    ("þjóðlag", "folk song", "noun", "THYOHTH-lahg"),
    ("trúarbrögð", "religion", "noun", "TROO-ar-bruhgth"),
    ("helgisiður", "ritual", "noun", "HEL-gi-SI-thur"),
    ("minningar", "memories", "noun", "MIN-ning-ar"),
    ("erfðir", "inheritance", "noun", "ERV-thir"),
    ("kynslóð", "generation", "noun", "KIN-slohth"),
    ("að halda í heiðri", "to honor", "verb", "ahth HAHL-da ee HAYTH-ri"),
    ("að varðveita", "to preserve", "verb", "ahth VARTH-vay-ta"),
    ("að halda áfram", "to continue", "verb", "ahth HAHL-da OW-fram"),
    ("að taka þátt í", "to participate in", "verb", "ahth TA-ka thowt ee"),
    ("að miðla", "to pass on", "verb", "ahth MITH-la"),
    ("aldagamall", "ancient", "adjective", "AHL-da-GA-mahtl"),
    ("hefðbundinn", "traditional", "adjective", "HEVTH-bun-din"),
    ("sérstakur", "special/unique", "adjective", "SYER-sta-kur"),
    ("þjóðlegur", "national", "adjective", "THYOHTH-le-gur"),
    ("menningarlegur", "cultural", "adjective", "MEN-ning-ar-le-gur"),

    # Lesson 22: Arts and literature
    ("listir", "arts", "noun", "LIS-tir"),
    ("bókmenntir", "literature", "noun", "BOHK-ment-ir"),
    ("myndlist", "visual art", "noun", "MIND-list"),
    ("tónlist", "music", "noun", "TOHN-list"),
    ("leiklist", "theater/drama", "noun", "LAYK-list"),
    ("dans", "dance", "noun", "dahns"),
    ("ljósmyndun", "photography", "noun", "LYOHS-min-dun"),
    ("höggmynd", "sculpture", "noun", "HUHG-mind"),
    ("málverk", "painting", "noun", "MOWL-verk"),
    ("skáldsaga", "novel", "noun", "SKOWLD-SA-ga"),
    ("ljóð", "poem", "noun", "lyohth"),
    ("leikrit", "play", "noun", "LAYK-rit"),
    ("listamaður", "artist", "noun", "LIS-ta-MA-thur"),
    ("höfundur", "author", "noun", "HUH-vun-dur"),
    ("tónskáld", "composer", "noun", "TOHN-skowld"),
    ("að skapa", "to create", "verb", "ahth SKA-pa"),
    ("að tjá", "to express", "verb", "ahth tyow"),
    ("að flytja", "to perform", "verb", "ahth FLIT-ya"),
    ("að túlka", "to interpret", "verb", "ahth TOOL-ka"),
    ("að dást að", "to admire", "verb", "ahth dowst ahth"),
    ("skapandi", "creative", "adjective", "SKA-pahn-di"),
    ("listrænn", "artistic", "adjective", "LIST-raitn"),
    ("fagur", "beautiful", "adjective", "FA-gur"),
    ("áhrifamikill", "influential", "adjective", "OW-hri-va-MI-kitl"),
    ("upplifun", "experience", "noun", "UP-li-vun"),

    # Lesson 23: History basics
    ("saga", "history/story", "noun", "SA-ga"),
    ("fortíð", "past", "noun", "FOR-teeth"),
    ("sögulegur", "historical", "adjective", "SUH-gu-le-gur"),
    ("fornöld", "antiquity", "noun", "FORN-uhld"),
    ("miðaldir", "Middle Ages", "noun", "MITH-AHL-dir"),
    ("nútími", "modern times", "noun", "NOO-tee-mi"),
    ("atburður", "event", "noun", "AHT-bur-thur"),
    ("tímabil", "era/period", "noun", "TEE-ma-bil"),
    ("byltingu", "revolution", "noun", "BIL-ting-u"),
    ("stríð", "war", "noun", "streeth"),
    ("friður", "peace", "noun", "FRITH-ur"),
    ("landnám", "settlement", "noun", "LAHND-nowm"),
    ("sjálfstæði", "independence", "noun", "SYOWLF-stai-thi"),
    ("konungur", "king", "noun", "KO-nung-ur"),
    ("drottning", "queen", "noun", "DROHT-ning"),
    ("að rannsaka", "to research", "verb", "ahth RAHN-sa-ka"),
    ("að uppgötva", "to discover", "verb", "ahth UP-guht-va"),
    ("að muna", "to remember", "verb", "ahth MU-na"),
    ("að læra af", "to learn from", "verb", "ahth LAI-ra ahv"),
    ("að endurtaka", "to repeat", "verb", "ahth EN-dur-TA-ka"),
    ("merkilegur", "significant", "adjective", "MER-ki-le-gur"),
    ("frægt", "famous", "adjective", "fraigt"),
    ("tímabundin", "temporary", "adjective", "TEE-ma-bun-din"),
    ("varanlegur", "permanent", "adjective", "VA-rahn-le-gur"),
    ("söguþráður", "historical narrative", "noun", "SUH-gu-THROW-thur"),

    # Lesson 24: Current events
    ("núverandi atburðir", "current events", "noun", "NOO-ve-rahn-di AHT-bur-thir"),
    ("heimsmál", "world affairs", "noun", "HAYMS-mowl"),
    ("pólitík", "politics", "noun", "POH-li-teek"),
    ("hagkerfi", "economy", "noun", "HAHG-ker-vi"),
    ("samfélag", "society", "noun", "SAHM-fyeh-lahg"),
    ("ríkisstjórn", "government", "noun", "REE-kis-styohrn"),
    ("kosningar", "elections", "noun", "KOS-ning-ar"),
    ("löggjöf", "legislation", "noun", "LUHG-gyuhv"),
    ("mannréttindi", "human rights", "noun", "MAHN-ryeht-in-di"),
    ("alþjóðasamfélag", "international community", "noun", "AHL-thyoh-tha-SAHM-fyeh-lahg"),
    ("samþykkt", "resolution", "noun", "SAHM-thikt"),
    ("kreppa", "crisis", "noun", "KREP-a"),
    ("þróun", "development", "noun", "THROH-un"),
    ("lausn", "solution", "noun", "loisn"),
    ("stefna", "policy", "noun", "STEV-na"),
    ("að kjósa", "to vote", "verb", "ahth KYOH-sa"),
    ("að mótmæla", "to protest", "verb", "ahth MOHT-mai-la"),
    ("að styðja", "to support", "verb", "ahth STITH-ya"),
    ("að andmæla", "to oppose", "verb", "ahth AHND-mai-la"),
    ("að ræða", "to discuss", "verb", "ahth RAI-tha"),
    ("umdeildur", "controversial", "adjective", "UM-dayld-ur"),
    ("mikilvægur", "important", "adjective", "MI-kil-VAI-gur"),
    ("aðkallandi", "urgent", "adjective", "ATH-KAHL-ahn-di"),
    ("alþjóðlegur", "international", "adjective", "AHL-thyohth-le-gur"),
    ("innlendur", "domestic", "adjective", "IN-len-dur"),

    # Lesson 25: Cultural differences
    ("menningarmunur", "cultural difference", "noun", "MEN-ning-ar-MU-nur"),
    ("fjölmenning", "multiculturalism", "noun", "FYUHL-men-ning"),
    ("aðlögun", "adaptation", "noun", "ATH-luh-gun"),
    ("samþætting", "integration", "noun", "SAHM-thait-ing"),
    ("fordómar", "prejudice", "noun", "FOR-DOH-mar"),
    ("umburðarlyndi", "tolerance", "noun", "UM-bur-thar-LIN-di"),
    ("virðing", "respect", "noun", "VIR-thing"),
    ("misskilningur", "misunderstanding", "noun", "MIS-skil-ning-ur"),
    ("samskipti", "communication", "noun", "SAHM-skip-ti"),
    ("siðferði", "ethics", "noun", "SITH-fer-thi"),
    ("táknmál", "sign language/symbols", "noun", "TOWKN-mowl"),
    ("líkamstjáning", "body language", "noun", "LEE-kahms-TYOW-ning"),
    ("hefðir", "customs", "noun", "HEV-thir"),
    ("gildi", "values", "noun", "GIL-di"),
    ("heimsmynd", "worldview", "noun", "HAYMS-mind"),
    ("að aðlagast", "to adapt", "verb", "ahth ATH-la-gast"),
    ("að skilja", "to understand", "verb", "ahth SKIL-ya"),
    ("að virða", "to respect", "verb", "ahth VIR-tha"),
    ("að læra", "to learn", "verb", "ahth LAI-ra"),
    ("að deila", "to share", "verb", "ahth DAY-la"),
    ("opinn", "open-minded", "adjective", "OH-pin"),
    ("lokaður", "closed-minded", "adjective", "LO-ka-thur"),
    ("fjölbreyttur", "diverse", "adjective", "FYUHL-brayt-ur"),
    ("sameiginlegur", "common/shared", "adjective", "SA-mayg-in-le-gur"),
    ("ólíkur", "different", "adjective", "OH-lee-kur"),

    # Lesson 26: Formal vs informal
    ("formlegt", "formal", "adjective", "FORM-legt"),
    ("óformlegt", "informal", "adjective", "OH-form-legt"),
    ("kurteisi", "politeness", "noun", "KUR-tay-si"),
    ("þú og þér", "informal and formal you", "phrase", "thoo og thyer"),
    ("hátíðlegt", "ceremonial", "adjective", "HOW-teeth-legt"),
    ("hversdagslegt", "everyday", "adjective", "KVERS-dahgs-legt"),
    ("forsetaávarpi", "presidential address", "noun", "FOR-se-ta-OW-var-pi"),
    ("slang", "slang", "noun", "slahng"),
    ("mállýska", "dialect", "noun", "MOWL-lees-ka"),
    ("staðalmál", "standard language", "noun", "STA-thahl-mowl"),
    ("háskólastíll", "academic style", "noun", "HOW-skoh-la-steel"),
    ("viðskiptastíll", "business style", "noun", "VITH-skip-ta-steel"),
    ("vinsamlegur", "friendly", "adjective", "VIN-sahm-le-gur"),
    ("afslappað", "relaxed", "adjective", "AHV-slahp-ahth"),
    ("hátíðlega", "formally", "adverb", "HOW-teeth-le-ga"),
    ("að ávarpa", "to address", "verb", "ahth OW-var-pa"),
    ("að nota", "to use", "verb", "ahth NO-ta"),
    ("að tala", "to speak", "verb", "ahth TA-la"),
    ("að skrifa", "to write", "verb", "ahth SKRI-va"),
    ("að þýða", "to translate", "verb", "ahth THEE-tha"),
    ("viðeigandi", "appropriate", "adjective", "VITH-ay-gahn-di"),
    ("óviðeigandi", "inappropriate", "adjective", "OH-vith-ay-gahn-di"),
    ("kurteis", "polite", "adjective", "KUR-tays"),
    ("ókurteis", "impolite", "adjective", "OH-kur-tays"),
    ("heiðursgestur", "guest of honor", "noun", "HAYTH-urs-GES-tur"),

    # Lesson 27: Idioms and expressions
    ("orðatiltæki", "idiom", "noun", "OR-tha-TIL-tai-ki"),
    ("máltæki", "saying", "noun", "MOWL-tai-ki"),
    ("sláandi", "striking", "adjective", "SLOW-ahn-di"),
    ("myndlíking", "metaphor", "noun", "MIND-lee-king"),
    ("samlíking", "simile", "noun", "SAHM-lee-king"),
    ("að slá í gegn", "to break through", "phrase", "ahth slow ee gyegn"),
    ("að detta í hug", "to occur to", "phrase", "ahth DET-a ee hug"),
    ("að standa á eigin fótum", "to stand on own feet", "phrase", "ahth STAHN-da ow AY-gin FOH-tum"),
    ("að sjá sóma sinn í", "to take pride in", "phrase", "ahth syow SOH-ma seen ee"),
    ("að gefa gaum að", "to pay attention to", "phrase", "ahth GYE-va goim ahth"),
    ("kominn til að vera", "here to stay", "phrase", "KO-min til ahth VE-ra"),
    ("það er úti um mig", "I'm done for", "phrase", "thahth er OO-ti um mig"),
    ("að taka mark á", "to take note of", "phrase", "ahth TA-ka mark ow"),
    ("að hafa í huga", "to keep in mind", "phrase", "ahth HA-va ee HU-ga"),
    ("að grípa tækifærið", "to seize opportunity", "phrase", "ahth GREE-pa TAI-ki-fair-ith"),
    ("að gera sér grein fyrir", "to realize", "verb", "ahth GYE-ra syer grayn FI-rir"),
    ("að koma til sögunnar", "to come into play", "phrase", "ahth KO-ma til SUH-gun-ar"),
    ("að leggja áherslu á", "to emphasize", "phrase", "ahth LEG-ya OW-hers-lu ow"),
    ("að taka undir", "to agree with", "phrase", "ahth TA-ka UN-dir"),
    ("að ná til", "to reach out to", "phrase", "ahth now til"),
    ("málsháttasafn", "collection of proverbs", "noun", "MOWLS-HOW-ta-SAHV-n"),
    ("táknrænn", "symbolic", "adjective", "TOWKN-raitn"),
    ("óbeinn", "indirect", "adjective", "OH-baytn"),
    ("beinn", "direct", "adjective", "baytn"),
    ("talað mál", "spoken language", "noun", "TA-lahth mowl"),

    # Lesson 28: Review - abstract concepts
    ("hugtök", "concepts", "noun", "HUG-tuhk"),
    ("hugmynd", "idea", "noun", "HUG-mind"),
    ("skilgreining", "definition", "noun", "SKIL-gray-ning"),
    ("merking", "meaning", "noun", "MER-king"),
    ("áhrif", "influence", "noun", "OW-hriv"),
    ("samhengi", "context", "noun", "SAHM-hen-gi"),
    ("þekking", "knowledge", "noun", "THEK-ing"),
    ("viska", "wisdom", "noun", "VIS-ka"),
    ("rökhugsun", "reasoning", "noun", "RUHK-hug-sun"),
    ("ályktun", "conclusion", "noun", "OW-lik-tun"),
    ("forsenda", "premise", "noun", "FOR-sen-da"),
    ("staðhæfing", "statement", "noun", "STAHTH-hai-ving"),
    ("rök", "argument", "noun", "ruhk"),
    ("sönnun", "proof", "noun", "SUHN-un"),
    ("gagnrýni", "criticism", "noun", "GAHGN-ree-ni"),
    ("að skilgreina", "to define", "verb", "ahth SKIL-gray-na"),
    ("að greina", "to analyze", "verb", "ahth GRAY-na"),
    ("að túlka", "to interpret", "verb", "ahth TOOL-ka"),
    ("að draga ályktanir", "to draw conclusions", "verb", "ahth DRA-ga OW-lik-ta-nir"),
    ("að rökstyðja", "to justify", "verb", "ahth RUHK-stith-ya"),
    ("óhlutbundinn", "abstract", "adjective", "OH-HLUT-bun-din"),
    ("hlutbundinn", "concrete", "adjective", "HLUT-bun-din"),
    ("flókinn", "complex", "adjective", "FLOH-kin"),
    ("einfaldur", "simple", "adjective", "AYN-fahl-dur"),
    ("djúpstæður", "profound", "adjective", "DYOOP-stai-thur"),

    # Lesson 29: Review - professional
    ("starfsþróun", "career development", "noun", "STARFS-THROH-un"),
    ("færni", "competence", "noun", "FAIR-ni"),
    ("leiðtogahæfni", "leadership skills", "noun", "LAYTH-to-ga-HAIV-ni"),
    ("samstarfshæfni", "teamwork skills", "noun", "SAHM-starfs-HAIV-ni"),
    ("samskiptahæfni", "communication skills", "noun", "SAHM-skip-ta-HAIV-ni"),
    ("tækniþekking", "technical knowledge", "noun", "TAIK-ni-THEK-ing"),
    ("verkefnastjórnun", "project management", "noun", "VER-kev-na-STYOHRN-un"),
    ("tímastjórnun", "time management", "noun", "TEE-ma-STYOHRN-un"),
    ("úrlausn", "solution", "noun", "OOR-loisn"),
    ("nýsköpun", "innovation", "noun", "NEE-skuh-pun"),
    ("að leiða", "to lead", "verb", "ahth LAY-tha"),
    ("að stýra", "to manage", "verb", "ahth STEE-ra"),
    ("að skipuleggja", "to organize", "verb", "ahth SKI-pu-LEG-ya"),
    ("að þróa", "to develop", "verb", "ahth THROH-a"),
    ("að innleiða", "to implement", "verb", "ahth IN-layth-a"),
    ("markmiðsdrifinn", "goal-oriented", "adjective", "MARK-miths-DRI-vin"),
    ("faglegur", "professional", "adjective", "FAHG-le-gur"),
    ("áreiðanlegur", "reliable", "adjective", "OW-rayth-ahn-le-gur"),
    ("vandaður", "careful/thorough", "adjective", "VAN-da-thur"),
    ("ábyrgur", "responsible", "adjective", "OW-bir-gur"),
    ("frumkvæði", "initiative", "noun", "FRUM-kvai-thi"),
    ("starfsviðtal", "performance review", "noun", "STARFS-VITH-tahl"),
    ("starfsframvinda", "career progression", "noun", "STARFS-FRAHM-vin-da"),
    ("hæfnimat", "competency assessment", "noun", "HAIV-ni-maht"),
    ("þjálfun", "training", "noun", "THYOWL-vun"),

    # Lesson 30: Comprehensive mastery
    ("vald", "mastery/command", "noun", "vahld"),
    ("tökum", "control/grasp", "noun", "TUH-kum"),
    ("undirstaða", "foundation", "noun", "UN-dir-STA-tha"),
    ("framfarir", "progress", "noun", "FRAHM-fa-rir"),
    ("stig", "level", "noun", "stig"),
    ("kunnátta", "proficiency", "noun", "KUN-owt-a"),
    ("sjálfsmat", "self-assessment", "noun", "SYOWLFS-maht"),
    ("markviss æfing", "deliberate practice", "noun", "MARK-vis AI-ving"),
    ("sjálfsþjálfun", "self-training", "noun", "SYOWLFS-THYOWL-vun"),
    ("endurgjöf", "feedback", "noun", "EN-dur-gyuhv"),
    ("umbætur", "improvement", "noun", "UM-bai-tur"),
    ("áskorun", "challenge", "noun", "OWS-ko-run"),
    ("að yfirstíga", "to overcome", "verb", "ahth I-vir-STEE-ga"),
    ("að fullkomna", "to perfect", "verb", "ahth FUL-kohm-na"),
    ("að viðhalda", "to maintain", "verb", "ahth VITH-HAHL-da"),
    ("að bæta", "to improve", "verb", "ahth BAI-ta"),
    ("að þjálfa", "to train", "verb", "ahth THYOWL-va"),
    ("að meta", "to evaluate", "verb", "ahth ME-ta"),
    ("að halda áfram", "to continue", "verb", "ahth HAHL-da OW-fram"),
    ("að útskrifast", "to graduate", "verb", "ahth OOT-skri-vast"),
    ("góður árangur", "good result", "noun", "GOH-thur OW-rahng-ur"),
    ("framúrskarandi", "excellent", "adjective", "FRAHM-oor-SKAR-ahn-di"),
    ("sjálfstraust", "confidence", "noun", "SYOWLFS-troist"),
    ("til hamingju", "congratulations", "phrase", "til HA-ming-yu"),
    ("velkominn aftur", "welcome back", "phrase", "VEL-ko-min AHF-tur"),
]

# Lesson title templates
LESSON_TITLES = {
    "A1": [
        "First Steps: Hello and Goodbye",
        "Meeting People",
        "Numbers and Counting",
        "Yes, No, and Thank You",
        "Asking Simple Questions",
        "Family Members",
        "Where Are You From?",
        "Jobs and Professions",
        "Around the City",
        "Finding Your Way",
        "Time and Days",
        "Food and Drink Basics",
        "At the Shop",
        "Weather Talk",
        "Colors All Around",
        "Morning Routines",
        "Common Actions",
        "Likes and Dislikes",
        "What Can You Do?",
        "Needs and Wants",
        "Being Polite",
        "At the Restaurant",
        "At the Hotel",
        "Phone Conversations",
        "Emergency Situations",
        "Travel Essentials",
        "Making Small Talk",
        "Review: Meeting People",
        "Review: Daily Life",
        "Putting It All Together",
    ],
    "A2": [f"A2 Lesson {i}: {VOCABULARY_CURRICULUM['A2']['themes'][i-1].replace('_', ' ').title()}" for i in range(1, 31)],
    "B1": [f"B1 Lesson {i}: {VOCABULARY_CURRICULUM['B1']['themes'][i-1].replace('_', ' ').title()}" for i in range(1, 31)],
}
